main – KORC
main Program
257 statements
Source File
Uses
korc_types
korc_units
korc_hpc
korc_HDF5
korc_fields
korc_ppusher
korc_interp
korc_collisions
korc_initialize
korc_finalize
korc_profiles
korc_input
korc_m3d_c1
Note
Main function of KORC.
The main program contains the calls to the main functions and subroutines. Also, it contains the variables that control the behavior of the core of KORC and all other external/optional modules.
Order of KORC operations
Communication and Timing
1. Parallel Communications
Subroutine initialize_communications in korc_hpc that initializes MPI and OpenMP communications.
2. Timers
Subroutine timing_KORC in korc_hpc that times the execution of any parallel sections of KORC.
Initialization
1. HDF5
Subroutine initialize_HDF5 in korc_HDF5 that initializes HDF5 library.
2. Initialize korc parameters
Subroutine initialize_korc_parameters in korc_initialize that initializes paths and KORC parameters through load_korc_params on MPI processes.
3. Initialize fields
Subroutine initialize_fields in korc_fields that initializes parameters of the EM fields, either analytically or from an external HDF5 file. Reads in &analytical_fields_params and &externalPlasmaModel namelists from input file.
4. Initialize Profiles
Subroutine initialize_profiles in korc_profiles that initializes parameters of the plasma profiles, either analytically or from an external HDF5 file. Reads in &plasmaProfiles namelist from input file. Only initialized if collisions (params%collisions==T) are
5. Initialize Particle Velocity Phase Space
Subroutine initialize_particles in korc_initialize that initializes particle parameters from &amplasma_species namelist, allocates arrays for individual particles, including location, velocity, local EM fields and plasma profiles, etc., and calls initial_energy_pitch_dist to assign particles' energy and pitch angle according to the chosen distribution.
9. Compute Characteristic Plasma Parameters
Subroutine compute_charcs_plasma_params in korc_units calculates the characteristic plasma parameters params%cpp that are used for normalizations. Also finds the maximum non-relativistic and relativistic cyclotron frequencies to be used for setting the timstep for the time-evolution algorithms.
6. Initialize Collision Parameters
Subroutine initialize_collision_params in korc_collisions that initializes collision parameters for the SS (single-species) and MS (multiple-species) data types, reading in namefiles from the KORC input file. MS reads in namelist &CollisionParamsMultipleSpecies while SS reads in namelist &CollisionParamsSingleSpecies.
10. Define Time Step
Subroutine define_time_step in korc_initialize either loads time-stepping parameters for a restart, or defines new parameters based on a maximum timestep set by the inverse of the relativistic cyclotron frequency.
11. Initialize Particle Pusher
12. Normalize Variables
Subroutine normalize_variables in korc_units normalizes variables consistent with characteristic plasma parameters calculated in compute_charcs_plasma_params.
13. Normalize Collision Parameters
Subroutine normalize_collisions_params in korc_collisions that normalizes collision parameters for the SS (single-species) and MS (multiple-species) data types.
14. Define Collision Time Step
Subroutine define_collisions_time_step in korc_collisions that sets subcycling iteration number for collisions based off of the collision frequency model used.
15. Initialize Fields Interpolant
Subroutine initialize_fields_interpolant in korc_interp calls EZspline subroutines EZspline_init for memory allocation and boundary condition setup and EZspline_setup to compute the necessary cubic coefficients needed for subsequent field interpolations. The magnetic field can be defined in terms of an axisymmetric scalar flux function, axisymmetric field, or 3D field, while the electric field can be defined as an axisymmetric or 3D field.
16. Initialize Profiles Interpolant
Subroutine initialize_profiles_interpolant in korc_interp calls EZspline subroutines EZlinear_init for axisymmetric (flux-surface quantities) or EZspline_init for 3D profiles for memory allocation and boundary condition setup and EZspline_setup to compute the necessary cubic coefficients needed for subsequent field interpolations. Only initialized if collisions (params%collisions==T) are present for ne, Te, Zeff
17. Set Particle Initial Conditions
Subroutine set_up_particles_ic in korc_initialize calls subroutines to prescribe initial conditions or load them from file for a restart. Initial spatial values are prescribed with intitial_spatial_distribution in korc_spatial_distribution and initial velocity values are prescribed with initial_gyro_distribution in korc_velocity_distribution.
18. Save Simulation and Collision Parameters
Subroutines save_simulation_parameters in korc_HDF5 and save_collision_params in korc_collisions call subroutines to save simulation and collision parameters.
Calls
Contents
Variables
params spp F P it mpierr
Source Code
main
Variables
Type Attributes Name Initial
type(KORC_PARAMS) :: params
Contains the parameters that control the core of KORC: time steping, output list, etc.
type(SPECIES), DIMENSION(:), ALLOCATABLE :: spp
Contains the initial parameters of each species, which can be different electrons with different distribution functions.
type(FIELDS) :: F
and electric fields, or in the case of using external fields it contains the data used in the interpolations. See korc_fields for details.
type(PROFILES) :: P
or in the case of using external fields it contains the data used in the interpolations. See korc_profiles for details.
integer(kind=ip) :: it
Time iteration
integer :: mpierr
Source Code
program main
  !! @note  Main function of KORC. @endnote
  !! The main program contains the calls to the main functions and subroutines.
  !! Also, it contains the variables that control
  !! the behavior of the core of KORC and all other external/optional modules.
  use korc_types
  use korc_units
  use korc_hpc
  use korc_HDF5
  use korc_fields
  use korc_ppusher
  use korc_interp
  use korc_collisions
  use korc_initialize
  use korc_finalize
  use korc_profiles
  use korc_input
  use korc_m3d_c1
  implicit none
  TYPE(KORC_PARAMS) :: params
  !! Contains the parameters that control the core of KORC:
  !! time steping, output list, etc.
  TYPE(SPECIES), DIMENSION(:), ALLOCATABLE :: spp
  !! Contains the initial parameters of each species, which
  !! can be different electrons with different
  !! distribution functions.
  TYPE(FIELDS) :: F
  !! F: Contains the parameters of the analytical magnetic
  !! and electric fields, or in the case of using
  !! external fields it contains the data used in the interpolations.
  !!See [[korc_fields(module)]] for details.
  TYPE(PROFILES) :: P
  !! P: Contains the parameters of the analytical plasma profiles,
  !! or in the case of using external
  !! fields it contains the data used in the interpolations.
  !! See [[korc_profiles(module)]] for details.
  INTEGER(ip) :: it
  !! Time iteration
    INTEGER                 :: mpierr
  call initialize_communications(params)
  !!<h2>Order of KORC operations</h2>
  !!
  !!<h3>Communication and Timing</h3>
  !! <h4>1\. Parallel Communications</h4>
  !!
  !! Subroutine [[initialize_communications]] in [[korc_hpc]] that
  !! initializes MPI and OpenMP communications.
  call timing_KORC(params)
  !! <h4>2\. Timers</h4>
  !!
  !! Subroutine [[timing_KORC]] in [[korc_hpc]] that times the
  !! execution of any parallel sections of KORC.
  ! * * * INITIALIZATION STAGE * * *!
  call initialize_HDF5()
  !!<h3>Initialization</h3>
  !!
  !! <h4>1\. HDF5</h4>
  !!
  !! Subroutine [[initialize_HDF5]] in [[korc_HDF5]] that initializes
  !! HDF5 library.
  call initialize_korc_parameters(params)
  !! <h4>2\. Initialize korc parameters</h4>
  !!
  !! Subroutine [[initialize_korc_parameters]] in [[korc_initialize]] that
  !! initializes paths and KORC parameters through [[load_korc_params]]
  !! on MPI processes.
  call initialize_fields(params,F)
  !! <h4>3\. Initialize fields</h4>
  !!
  !! Subroutine [[initialize_fields]] in [[korc_fields]] that initializes
  !! parameters of the EM fields, either analytically or from an external HDF5
  !! file. Reads in &amp;analytical_fields_params and
  !! &amp;externalPlasmaModel namelists from input file.
  call initialize_profiles(params,P,F)
  !! <h4>4\. Initialize Profiles</h4>
  !!
  !! Subroutine [[initialize_profiles]] in [[korc_profiles]] that initializes
  !! parameters of the plasma profiles, either analytically or from an
  !! external HDF5
  !! file. Reads in &amp;plasmaProfiles namelist from input file.
  !! Only initialized if collisions (params%collisions==T) are
  call initialize_particles(params,F,P,spp) ! Initialize particles
  !! <h4>5\. Initialize Particle Velocity Phase Space</h4>
  !!
  !! Subroutine [[initialize_particles]] in [[korc_initialize]] that
  !! initializes particle parameters from &amplasma_species namelist,
  !! allocates arrays for individual particles, including location, velocity,
  !! local EM fields and plasma profiles, etc., and
  !! calls [[initial_energy_pitch_dist]] to assign particles' energy and pitch
  !! angle according to the chosen distribution.
!  write(output_unit_write,'("init eta: ",E17.10)') spp(1)%vars%eta
#ifdef M3D_C1
  if (TRIM(params%field_model) .eq. 'M3D_C1') then
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * INITIALIZING M3D-C1 INTERFACE * * * *"
     endif
     call initialize_m3d_c1(params, F, P, spp,.true.)
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) "* * * * * * * * * * * * * * * * * * * * * * *"
     endif
  endif
#endif
  call compute_charcs_plasma_params(params,spp,F)
  !! <h4>9\. Compute Characteristic Plasma Parameters</h4>
  !!
  !! Subroutine [[compute_charcs_plasma_params]] in [[korc_units]] calculates
  !! the characteristic plasma parameters params%cpp that are used for normalizations.
  !! Also finds the maximum non-relativistic and relativistic cyclotron frequencies
  !! to be used for setting the timstep for the time-evolution algorithms.
  call initialize_collision_params(params,spp,P,F)
  !! <h4>6\. Initialize Collision Parameters</h4>
  !!
  !! Subroutine [[initialize_collision_params]] in [[korc_collisions]] that
  !! initializes collision parameters for the SS (single-species) and MS
  !! (multiple-species) data types, reading in namefiles from the KORC input file.
  !! MS reads in namelist &CollisionParamsMultipleSpecies while SS reads in
  !! namelist &CollisionParamsSingleSpecies.
  call define_time_step(params,F)
  !! <h4>10\. Define Time Step</h4>
  !!
  !! Subroutine [[define_time_step]] in [[korc_initialize]] either loads
  !! time-stepping parameters for a restart, or defines new parameters based
  !! on a maximum timestep
  !! set by the inverse of the relativistic cyclotron frequency.
  call initialize_particle_pusher(params)
  !! <h4>11\. Initialize Particle Pusher</h4>
  if (params%SC_E) then
     call define_SC_time_step(params,F)
  end if
  call normalize_variables(params,spp,F,P)
  !! <h4>12\. Normalize Variables</h4>
  !!
  !! Subroutine [[normalize_variables]] in [[korc_units]] normalizes
  !! variables consistent with characteristic plasma parameters
  !! calculated in [[compute_charcs_plasma_params]].
  call normalize_collisions_params(params)
  !! <h4>13\. Normalize Collision Parameters </h4>
  !!
  !! Subroutine [[normalize_collisions_params]] in [[korc_collisions]] that
  !! normalizes collision parameters for the SS (single-species) and MS
  !! (multiple-species) data types.
  call define_collisions_time_step(params)
  !! <h4>14\. Define Collision Time Step</h4>
  !!
  !! Subroutine [[define_collisions_time_step]] in [[korc_collisions]] that
  !! sets subcycling iteration number for collisions based off of the collision
  !! frequency model used.
  ! *** *** *** *** *** ***   *** *** *** *** *** *** ***
  ! *** BEYOND THIS POINT VARIABLES ARE DIMENSIONLESS ***
  ! *** *** *** *** *** ***   *** *** *** *** *** *** ***
  call initialize_fields_interpolant(params,F)
  !! <h4>15\. Initialize Fields Interpolant</h4>
  !!
  !! Subroutine [[initialize_fields_interpolant]] in [[korc_interp]] calls
  !! EZspline
  !! subroutines EZspline_init for memory allocation and boundary condition
  !! setup
  !! and EZspline_setup to compute the necessary cubic coefficients needed
  !! for subsequent
  !! field interpolations. The magnetic field can be defined in terms of an
  !! axisymmetric
  !! scalar flux function, axisymmetric field, or 3D field, while the
  !! electric field
  !! can be defined as an axisymmetric or 3D field.
  call initialize_profiles_interpolant(params,P)
  !! <h4>16\. Initialize Profiles Interpolant</h4>
  !!
  !! Subroutine [[initialize_profiles_interpolant]] in [[korc_interp]]
  !! calls EZspline
  !! subroutines EZlinear_init for axisymmetric (flux-surface quantities) or
  !! EZspline_init for 3D profiles for memory allocation and boundary
  !! condition setup
  !! and EZspline_setup to compute the necessary cubic coefficients needed
  !! for subsequent
  !! field interpolations.
  !! Only initialized if collisions (params%collisions==T) are present for
  !! ne, Te, Zeff
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("* * * * INITIALIZING INITIAL CONDITIONS * * * *",/)')
  end if
  call set_up_particles_ic(params,F,spp,P)
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("* * * * * * * * * * * * * * * * * * * * * * * *",/)')
  end if
!  write(output_unit_write,'("post ic eta: ",E17.10)') spp(1)%vars%eta
  !! <h4>17\. Set Particle Initial Conditions</h4>
  !!
  !! Subroutine [[set_up_particles_ic]] in [[korc_initialize]] calls
  !! subroutines to prescribe initial conditions or load them
  !! from file for a restart. Initial spatial values are prescribed with
  !! [[intitial_spatial_distribution]] in [[korc_spatial_distribution]] and
  !! initial velocity values are prescribed with [[initial_gyro_distribution]]
  !! in [[korc_velocity_distribution]].
!  if (minval(spp(1)%vars%Y(:,1)).lt.1._rp/params%cpp%length) stop 'error with init'
  ! * * * INITIALIZATION STAGE * * *
  flush(output_unit_write)
!  write(output_unit_write,'("GC init eta: ",E17.10)') spp(1)%vars%eta
  if (.NOT.(params%restart.OR.params%proceed.or.params%reinit)) then
     if (params%orbit_model(1:2).eq.'FO') then
        call FO_init(params,F,spp,.true.,.false.)
     else if (params%orbit_model(1:2).eq.'GC') then
        call GC_init(params,F,spp)
     end if
     if (params%SC_E) then
        if (params%field_model(1:1).eq.'A') then
           call init_SC_E1D(params,F,spp(1))
        else if (params%field_model(1:1).eq.'E') then
           call init_SC_E1D_FS(params,F,spp(1))
        end if
     end if
  else
     call get_fields(params,spp(1)%vars,F)
     if (params%SC_E) then
        if (params%field_model(1:1).eq.'A') then
           call reinit_SC_E1D(params,F)
        else if (params%field_model(1:1).eq.'E') then
           call reinit_SC_E1D_FS(params,F)
        end if
     end if
  end if
  ! * * * SAVING INITIAL CONDITION AND VARIOUS SIMULATION PARAMETERS * * * !
  call save_simulation_parameters(params,spp,F,P)
  call save_collision_params(params)
  !! <h4>18\. Save Simulation and Collision Parameters</h4>
  !!
  !! Subroutines [[save_simulation_parameters]] in [[korc_HDF5]] and
  !! [[save_collision_params]] in [[korc_collisions]] call
  !! subroutines to save simulation and collision parameters.
  if (.NOT.(params%restart.OR.params%proceed)) then
     call save_simulation_outputs(params,spp,F) ! Save initial condition
  end if
  ! * * * SAVING INITIAL CONDITION AND VARIOUS SIMULATION PARAMETERS * * * !
!  write(output_unit_write,'("pre ppusher loop eta: ",E17.10)') spp(1)%vars%eta
  flush(output_unit_write)
  call timing_KORC(params)
  if (params%orbit_model(1:2).eq.'FO'.and.params%field_model(1:3).eq.'ANA') then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOeqn_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'FO'.and.params%field_model(1:3).eq.'EXT') then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOinterp_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'FO'.and.params%field_model.eq.'M3D_C1') then
     call FO_init(params,F,spp,.false.,.true.)
     ! Initial half-time particle push
     do it=params%ito,params%t_steps,params%t_skip
        call adv_FOm3dc1_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'eqn'.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip*params%t_it_SC
        call adv_GCeqn_top(params,F,P,spp)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip*params%t_it_SC,rp)*params%dt
        params%it = it-1_ip+params%t_skip*params%t_it_SC
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.params%field_model(10:12).eq.'PSI'.and. &
       params%SC_E.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi_top_FS(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and.(.not.F%Dim2x1t).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and.F%Dim2x1t.and.(.not.F%ReInterp_2x1t).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psi2x1t_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'PSI'.OR. &
       params%field_model(12:14).eq.'PSI').and. &
       (.not.params%SC_E).and.F%Dim2x1t.and.F%ReInterp_2x1t.and..not.params%field_model.eq.'M3D_C1') then
     if (params%mpi_params%rank .EQ. 0) then
        write(output_unit_write,*) 'time',F%X%PHI(F%ind_2x1t)*params%cpp%time
     end if
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_psiwE_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        F%ind_2x1t=F%ind_2x1t+1_ip
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'time',F%X%PHI(F%ind_2x1t)*params%cpp%time
        end if
        call initialize_fields_interpolant(params,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.F%dBfield.and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_2DBdB_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       F%axisymmetric_fields.and.(params%field_model(10:12).eq.'2DB'.or. &
       params%field_model(12:13).eq.'2D').and..not.(F%dBfield).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_B2D_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
         .not.(F%axisymmetric_fields).and.(F%dBfield).and. &
         (params%field_model(10:14).eq.'3DBdB').and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_3DBdB_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
         .not.(F%axisymmetric_fields).and.(F%dBfield).and. &
         .not.(params%field_model(10:14).eq.'3DBdB').and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_3DBdB1_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_eval.eq.'interp'.and. &
       .not.(F%axisymmetric_fields).and..not.(F%dBfield).and..not.params%field_model.eq.'M3D_C1') then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_B_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip,rp)*params%dt
        params%it = it-1_ip+params%t_skip
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_model.eq.'M3D_C1'.and. &
       .not.F%ReInterp_2x1t) then
     do it=params%ito,params%t_steps,params%t_skip
        call adv_GCinterp_m3dc1_top(params,spp,P,F)
        params%time = params%init_time &
             +REAL(it-1_ip+params%t_skip*params%t_it_SC,rp)*params%dt
        params%it = it-1_ip+params%t_skip*params%t_it_SC
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
     end do
  end if
  if (params%orbit_model(1:2).eq.'GC'.and.params%field_model.eq.'M3D_C1'.and. &
       F%ReInterp_2x1t) then
     do it=F%ind0_2x1t,params%time_slice
        if (it.gt.0) then
           call initialize_m3d_c1(params, F, P, spp,.false.)
           if (params%collisions) then
              call initialize_m3d_c1_imp(params,F,P, &
                   params%num_impurity_species,.false.)
           end if
        end if
        write(output_unit_write,*) 'tskip',params%t_skip
        flush(output_unit_write)
        call adv_GCinterp_m3dc1_top(params,spp,P,F)
        params%it = params%it+params%t_skip
        params%time = params%init_time &
             +REAL(params%it,rp)*params%dt
        call save_simulation_outputs(params,spp,F)
        call save_restart_variables(params,spp,F)
        F%ind_2x1t=F%ind_2x1t+1_ip
        if (params%mpi_params%rank .EQ. 0) then
           write(output_unit_write,*) 'KORC time ',params%time*params%cpp%time
           flush(output_unit_write)
        end if
     end do
  end if
  call timing_KORC(params)
  ! * * * FINALIZING SIMULATION * * *
  call finalize_HDF5()
  call finalize_interpolants(params)
  ! DEALLOCATION OF VARIABLES
  call deallocate_variables(params,F,P,spp)
  call deallocate_collisions_params(params)
  call finalize_communications(params)
  ! * * * FINALIZING SIMULATION * * *
  if (params%mpi_params%rank .EQ. 0) then
     write(output_unit_write,'("KORC ran successfully!")')
     close(output_unit_write)
  end if
end program main
Call graph
main calls adv_gcinterp_psi_top, finalize_communications, define_sc_time_step, initialize_hdf5, initialize_fields, save_simulation_parameters, initialize_profiles, save_collision_params, adv_gcinterp_2dbdb_top, reinit_sc_e1d_fs, timing_korc, adv_gcinterp_m3dc1_top, initialize_fields_interpolant, save_simulation_outputs, reinit_sc_e1d, adv_gcinterp_b_top, initialize_particles, adv_foeqn_top, adv_fom3dc1_top, define_time_step, deallocate_variables, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top, adv_gceqn_top, finalize_interpolants, initialize_communications, initialize_profiles_interpolant, initialize_m3d_c1, save_restart_variables, compute_charcs_plasma_params, adv_gcinterp_3dbdb1_top, define_collisions_time_step, finalize_hdf5, initialize_particle_pusher, fo_init, deallocate_collisions_params, adv_fointerp_top, gc_init, initialize_korc_parameters, adv_gcinterp_psi2x1t_top, set_up_particles_ic, adv_gcinterp_b2d_top, initialize_m3d_c1_imp, normalize_variables, normalize_collisions_params, adv_gcinterp_psi_top_fs, initialize_collision_params
adv_gcinterp_psi_top calls calculate_gcfields_p, advance_fpinterp_vars
finalize_communications calls finalize_mpi
initialize_hdf5 calls h5tcopy_f, h5tget_size_f, h5open_f
initialize_fields calls load_1d_fs_from_hdf5, load_field_data_from_hdf5, allocate_2d_fields_arrays, load_prev_iter, allocate_3d_fields_arrays, load_dim_data_from_hdf5, allocate_1d_fs_arrays, korc_abort, initialize_gc_fields_3d, which_fields_in_file, initialize_gc_fields
save_simulation_parameters calls save_1d_array_to_hdf5, save_string_parameter, rsave_3d_array_to_hdf5, rsave_2d_array_to_hdf5, h5eset_auto_f, save_to_hdf5, h5fclose_f, h5gclose_f
initialize_profiles calls allocate_2d_profiles_arrays, load_profiles_data_from_hdf5
save_collision_params calls save_params_ms, save_params_ss
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
reinit_sc_e1d_fs calls initialize_sc1d_field_interpolant_fs
timing_korc calls mpi_gather, mpi_wtime, mpi_barrier
initialize_fields_interpolant calls ezspline_allocated, ezspline_error, ezspline_init, ezspline_setup
save_simulation_outputs calls save_1d_array_to_hdf5, rsave_2d_array_to_hdf5, h5fclose_f, h5gclose_f
reinit_sc_e1d calls initialize_sc1d_field_interpolant
adv_gcinterp_b_top calls advance_fpinterp_vars
initialize_particles calls dr, xtrace, eno, sigmaz, spong_b, spong_dlam, dz, phio, zo, eo_lims, spong_w, ro, initial_energy_pitch_dist, sigmar
adv_foeqn_top calls advance_foeqn_vars, advance_fp3deqn_vars, analytical_fields_p
adv_fom3dc1_top calls cart_to_cyl_p, advance_fp3dinterp_vars, advance_fom3dc1_vars, get_m3d_c1_fomagnetic_fields_p, get_m3d_c1_vector_potential_p, get_m3d_c1_foelectric_fields_p
define_time_step calls load_prev_time, load_time_stepping_params
deallocate_variables calls deallocate_fields_arrays, deallocate_profiles_arrays
adv_gcinterp_psiwe_top calls calculate_gcfields_p, advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
adv_gceqn_top calls analytical_fields_bmag_p, calculate_sc_p, advance_fpeqn_vars, rad2deg, calculate_sc_e1d
finalize_interpolants calls ezspline_allocated
initialize_communications calls omp_get_num_procs, omp_get_num_threads, initialize_mpi
initialize_profiles_interpolant calls ezspline_error, ezspline_init, ezspline_setup
initialize_m3d_c1 calls load_prev_iter, fio_open_source, fio_get_real_field_parameter, fio_get_field, fio_get_options, fio_allocate_search_hint, fio_set_int_option
save_restart_variables calls mpi_gather, save_1d_array_to_hdf5, rsave_2d_array_to_hdf5, save_to_hdf5, h5fclose_f, h5gclose_f
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
define_collisions_time_step calls nu_par, nu_s, nu_d, nu_s_fio, nu_d_fio
finalize_hdf5 calls h5close_f
fo_init calls cart_to_cyl_p, cross, interp_fofields_p, get_m3d_c1_fomagnetic_fields_p, analytical_fields_p, interp_fofields1_p, get_m3d_c1_vector_potential_p, get_m3d_c1_foelectric_fields_p
deallocate_collisions_params calls deallocate_params_ms
adv_fointerp_top calls cart_to_cyl_p, advance_fointerp_vars, advance_fp3dinterp_vars, interp_fofields_p, interp_fofields1_p
gc_init calls cross, add_analytical_e_p, deg2rad
initialize_korc_parameters calls load_korc_params, mpi_barrier, read_namelist
adv_gcinterp_psi2x1t_top calls calculate_gcfields_2x1t_p, advance_fpinterp_vars
set_up_particles_ic calls init_random_seed, load_particles_ic, initial_gyro_distribution, intitial_spatial_distribution
adv_gcinterp_b2d_top calls advance_fpinterp_vars
initialize_m3d_c1_imp calls fio_make_species, fio_open_source, fio_get_field, fio_get_options, fio_set_int_option
normalize_collisions_params calls normalize_params_ms, normalize_params_ss
adv_gcinterp_psi_top_fs calls calculate_sc_p_fs, calculate_sc_e1d_fs, advance_fpinterp_vars
initialize_collision_params calls initialize_m3d_c1_imp, load_params_ss, load_params_ms
load_1d_fs_from_hdf5 calls h5fclose_f, h5fopen_f, load_array_from_hdf5
advance_fointerp_vars calls include_coulombcollisions_fo_p, radiation_force_p
nu_par calls ca
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
load_field_data_from_hdf5 calls h5fclose_f, load_from_hdf5, h5fopen_f, load_array_from_hdf5
nu_s calls cf
allocate_2d_fields_arrays calls allocate_v_field_2d
save_1d_array_to_hdf5 calls rsave_1d_array_to_hdf5, isave_1d_array_to_hdf5
save_string_parameter calls h5tcopy_f, h5dwrite_vl_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5tset_strpad_f
load_prev_iter calls h5fclose_f, mpi_bcast, load_from_hdf5, h5fopen_f
rsave_3d_array_to_hdf5 calls h5dwrite_f, h5sclose_f, h5screate_simple_f, h5dclose_f
initialize_sc1d_field_interpolant_fs calls ezspline_allocated, ezspline_error, ezspline_init, ezspline_setup
allocate_3d_fields_arrays calls allocate_v_field_3d
save_params_ms calls save_1d_array_to_hdf5, save_string_parameter, save_to_hdf5, h5fclose_f, h5gclose_f
rsave_2d_array_to_hdf5 calls h5dwrite_f, h5sclose_f, h5screate_simple_f, h5dclose_f
load_params_ss calls gammac_wu, clogee_wu, vte_wu, clogei_wu
advance_fpeqn_vars calls include_coulombcollisions_gc_p
save_to_hdf5 calls i8save_to_hdf5, i4save_to_hdf5, i2save_to_hdf5, i1save_to_hdf5, rsave_to_hdf5
calculate_gcfields_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
load_prev_time calls h5fclose_f, mpi_bcast, load_from_hdf5, h5fopen_f
advance_foeqn_vars calls include_coulombcollisions_fo_p, radiation_force_p
advance_fom3dc1_vars calls include_coulombcollisions_fo_p, radiation_force_p
load_dim_data_from_hdf5 calls h5fclose_f, load_from_hdf5, h5fopen_f
load_particles_ic calls h5fclose_f, korc_abort, h5fopen_f, load_array_from_hdf5
nu_d calls cb_ei, cb_ee
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
allocate_1d_fs_arrays calls h5fclose_f, load_from_hdf5, h5fopen_f
interp_fofields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
calculate_sc_e1d_fs calls initialize_sc1d_field_interpolant_fs, mpi_allreduce
load_time_stepping_params calls h5fclose_f, mpi_bcast, load_from_hdf5, h5fopen_f
korc_abort calls mpi_barrier, mpi_abort
nu_s_fio calls cf_fio
which_fields_in_file calls h5fclose_f, h5fopen_f
get_m3d_c1_fomagnetic_fields_p calls fio_eval_field
read_namelist calls mpi_barrier, korc_abort, rmcoment
calculate_gcfields_2x1t_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
save_params_ss calls save_string_parameter, save_to_hdf5, h5fclose_f, h5gclose_f
analytical_fields_p calls cart_to_tor_check_if_confined_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
initial_energy_pitch_dist calls mpi_barrier
initialize_sc1d_field_interpolant calls ezspline_allocated, ezspline_error, ezspline_init, ezspline_setup
load_profiles_data_from_hdf5 calls allocate_2d_profiles_arrays, h5fclose_f, load_from_hdf5, allocate_3d_profiles_arrays, h5fopen_f, load_array_from_hdf5
interp_fofields1_p calls ezspline_error, calculate_magnetic_field_p, ezspline_interp, check_if_in_fields_domain_p
initialize_mpi calls mpi_barrier, mpi_init, mpi_comm_rank, mpi_bcast, mpi_comm_size, mpi_cart_create, mpi_abort, set_paths, mpi_initialized, mpi_reduce
load_params_ms calls zj_mult, zo_mult
get_m3d_c1_vector_potential_p calls fio_eval_field
finalize_mpi calls mpi_barrier, mpi_finalized, mpi_finalize
calculate_sc_e1d calls initialize_sc1d_field_interpolant, mpi_allreduce
intitial_spatial_distribution calls korc_abort
nu_d_fio calls cb_ei_fio, cb_ee
get_m3d_c1_foelectric_fields_p calls fio_eval_field
cf_fio calls psi, clogee, h_j
gammac_wu calls clogee_wu
cb_ei_fio calls clogei, clogee, g_j
clogee_wu calls vte_wu, clog0_wu
include_coulombcollisions_fo_p calls cart_to_cyl_p, unitvectors_p, interp_focollision_p, dca_sd, analytical_profiles_p, cf_sd, get_random, cb_ee_sd, cb_ei_sd, ca_sd
calculate_magnetic_field_p calls ezspline_error, ezspline_interp, ezspline_gradient
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
i8save_to_hdf5 calls h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
i4save_to_hdf5 calls h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
i2save_to_hdf5 calls h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
load_array_from_hdf5 calls rload_2d_array_from_hdf5, rload_1d_array_from_hdf5, rload_3d_array_from_hdf5
include_coulombcollisions_gc_p calls calculate_gcfields_p, calculate_gcfields_2x1t_p, add_analytical_e_p, interp_focollision_p, dca_sd, calculate_gcfieldswe_p, analytical_profiles_p, calculate_2dbdbfields_p, calculate_gcfields_p_fs, analytical_fields_gc_p, interp_fields_3d_p, cf_sd, get_random, cb_ee_sd, cb_ei_sd, interp_fields_p, ca_sd
cb_ei calls clogei, clogee, g_j
i1save_to_hdf5 calls h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
rsave_1d_array_to_hdf5 calls h5tcopy_f, h5dwrite_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
set_paths calls korc_abort
cb_ee calls psi
cf calls psi, clogee, h_j
clogei_wu calls vte_wu, clog0_wu
ca calls psi
rsave_to_hdf5 calls h5tcopy_f, h5dwrite_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
isave_1d_array_to_hdf5 calls h5tcopy_f, h5dwrite_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
interp_focollision_p calls ezspline_error, ezspline_interp, check_if_in_profiles_domain_p
dca_sd calls psi, gammacee, vte
calculate_gcfieldswe_p calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
clogei calls vte, clog0
iload_from_hdf5 calls h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls h5dclose_f, h5dread_f
calculate_2dbdbfields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
calculate_gcfields_p_fs calls ezspline_error, ezspline_derivative, check_if_in_fields_domain_p
interp_fields_3d_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
cf_sd calls psi, clogee, h_j, gammacee, vte
get_random calls random_get_number_u, omp_get_thread_num
cb_ee_sd calls psi, gammacee, vte, delta
clogee calls vte, clog0
rload_3d_array_from_hdf5 calls h5dclose_f, h5dread_f
rload_from_hdf5 calls h5dclose_f, h5dread_f
cb_ei_sd calls clogei, clogee, g_j, gammacee, vte
interp_fields_p calls ezspline_error, ezspline_interp, check_if_in_fields_domain_p
ca_sd calls psi, gammacee, vte
gammacee calls clogee
delta calls vte