adv_GCeqn_top – KORC
adv_GCeqn_top Subroutine
80 statements
Source File
public subroutine adv_GCeqn_top(params, F, P, spp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
type(FIELDS), intent(inout) :: F
An instance of the KORC derived type FIELDS.
type(PROFILES), intent(in) :: P
An instance of the KORC derived type PROFILES.
type(SPECIES), intent(inout), DIMENSION(:), ALLOCATABLE :: spp
An instance of the derived type SPECIES containing all the parameters and simulation variables of the different species in the simulation.
Calls
Called by
Contents
Source Code
adv_GCeqn_top
Source Code
  subroutine adv_GCeqn_top(params,F,P,spp)
    TYPE(KORC_PARAMS), INTENT(INOUT)                           :: params
    !! Core KORC simulation parameters.
    TYPE(FIELDS), INTENT(INOUT)                                   :: F
    !! An instance of the KORC derived type FIELDS.
    TYPE(PROFILES), INTENT(IN)                                 :: P
    !! An instance of the KORC derived type PROFILES.
    TYPE(SPECIES), DIMENSION(:), ALLOCATABLE, INTENT(INOUT)    :: spp
    !! An instance of the derived type SPECIES containing all the parameters
    !! and simulation variables of the different species in the simulation.
    REAL(rp), DIMENSION(params%pchunk)               :: Bmag
    REAL(rp),DIMENSION(params%pchunk) :: Y_R,Y_PHI,Y_Z
    REAL(rp),DIMENSION(params%pchunk) :: B_R,B_PHI,B_Z,E_PHI
    REAL(rp),DIMENSION(params%pchunk) :: PSIp
    REAL(rp),DIMENSION(params%pchunk) :: V_PLL,V_MU
    REAL(rp) :: B0,EF0,R0,q0,lam,ar,m_cache,q_cache,ne0,Te0,Zeff0
    INTEGER(is),DIMENSION(params%pchunk)  :: flagCon,flagCol
    LOGICAL                                                    :: ss_collisions
    !! Logical variable that indicates if collisions are included in
    !! the simulation.
    INTEGER                                                    :: ii
    !! Species iterator.
    INTEGER                                                    :: pp
    !! Particles iterator.
    INTEGER                                                    :: cc,pchunk
    !! Chunk iterator.
    INTEGER(ip)                                                    :: tt
    INTEGER(ip)                                                    :: ttt
    !! time iterator.
    real(rp),dimension(F%dim_1D) :: Vden,Vdenave,VdenOMP
    do ii = 1_idef,params%num_species
       pchunk=params%pchunk
       q_cache=spp(ii)%q
       m_cache=spp(ii)%m
       do ttt=1_ip,params%t_it_SC
          VdenOMP=0._rp
          !$OMP PARALLEL DO default(none) &
          !$OMP& FIRSTPRIVATE(E0,q_cache,m_cache,pchunk) &
          !$OMP& shared(F,P,params,ii,spp) &
          !$OMP& PRIVATE(pp,tt,ttt,Bmag,cc,Y_R,Y_PHI,Y_Z,V_PLL,V_MU, &
          !$OMP& flagCon,flagCol,B_R,B_PHI,B_Z,E_PHI,PSIp, &
          !$OMP& Vden,Vdenave) &
          !$OMP& REDUCTION(+:VdenOMP)
          do pp=1_idef,spp(ii)%ppp,pchunk
             !$OMP SIMD
             do cc=1_idef,pchunk
                Y_R(cc)=spp(ii)%vars%Y(pp-1+cc,1)
                Y_PHI(cc)=spp(ii)%vars%Y(pp-1+cc,2)
                Y_Z(cc)=spp(ii)%vars%Y(pp-1+cc,3)
                V_PLL(cc)=spp(ii)%vars%V(pp-1+cc,1)
                V_MU(cc)=spp(ii)%vars%V(pp-1+cc,2)
                PSIp(cc)=spp(ii)%vars%PSI_p(pp-1+cc)
                flagCon(cc)=spp(ii)%vars%flagCon(pp-1+cc)
                flagCol(cc)=spp(ii)%vars%flagCol(pp-1+cc)
             end do
             !$OMP END SIMD
             if (.not.params%FokPlan) then
                Vdenave=0._rp
                do tt=1_ip,params%t_skip
                   !                   write(output_unit_write,*) params%mpi_params%rank,'Y_R',Y_R
                   call advance_GCeqn_vars(spp(ii)%vars,pp, &
                        tt+params%t_skip*(ttt-1),params, &
                        Y_R,Y_PHI, Y_Z,V_PLL,V_MU,flagCon,flagCol,q_cache,m_cache, &
                        B_R,B_PHI,B_Z,F,P,PSIp,E_PHI)
                   !                   write(output_unit_write,*) params%mpi_params%rank,'Y_R',Y_R
                   if (params%SC_E) then
                      call calculate_SC_p(params,F,B_R,B_PHI,B_Z,Y_R,Y_Z, &
                           V_PLL,V_MU,m_cache,flagCon,flagCol,Vden)
                      Vdenave=(Vdenave*REAL(tt-1_ip)+Vden)/REAL(tt)
                   end if
                end do !timestep iterator
                VdenOMP=VdenOMP+Vdenave
                !$OMP SIMD
                do cc=1_idef,pchunk
                   spp(ii)%vars%Y(pp-1+cc,1)=Y_R(cc)
                   spp(ii)%vars%Y(pp-1+cc,2)=Y_PHI(cc)
                   spp(ii)%vars%Y(pp-1+cc,3)=Y_Z(cc)
                   spp(ii)%vars%V(pp-1+cc,1)=V_PLL(cc)
                   spp(ii)%vars%V(pp-1+cc,2)=V_MU(cc)
                   spp(ii)%vars%flagCon(pp-1+cc)=flagCon(cc)
                   spp(ii)%vars%flagCol(pp-1+cc)=flagCol(cc)
                   spp(ii)%vars%B(pp-1+cc,1) = B_R(cc)
                   spp(ii)%vars%B(pp-1+cc,2) = B_PHI(cc)
                   spp(ii)%vars%B(pp-1+cc,3) = B_Z(cc)
                   spp(ii)%vars%PSI_P(pp-1+cc) = PSIp(cc)
                   spp(ii)%vars%E(pp-1+cc,2) = E_PHI(cc)
                end do
                !$OMP END SIMD
             else
                call advance_FPeqn_vars(params,Y_R,Y_PHI, &
                     Y_Z,V_PLL,V_MU,flagCon,flagCol,m_cache, &
                     F,P,PSIp)
                !$OMP SIMD
                do cc=1_idef,pchunk
                   spp(ii)%vars%V(pp-1+cc,1)=V_PLL(cc)
                   spp(ii)%vars%V(pp-1+cc,2)=V_MU(cc)
                   spp(ii)%vars%flagCol(pp-1+cc)=flagCol(cc)
                end do
                !$OMP END SIMD
             end if
             call analytical_fields_Bmag_p(pchunk,F,Y_R,Y_PHI,Y_Z, &
                  Bmag,E_PHI)
             !$OMP SIMD
             do cc=1_idef,pchunk
                spp(ii)%vars%g(pp-1+cc)=sqrt(1+V_PLL(cc)**2+ &
                     2*V_MU(cc)*Bmag(cc)*m_cache)
                spp(ii)%vars%eta(pp-1+cc) = rad2deg(atan2(sqrt(2*m_cache* &
                     Bmag(cc)*spp(ii)%vars%V(pp-1+cc,2)), &
                     spp(ii)%vars%V(pp-1+cc,1)))
             end do
             !$OMP END SIMD
          end do !particle chunk iterator
          !$OMP END PARALLEL DO
          if (params%SC_E) then
             call calculate_SC_E1D(params,F,VdenOMP)
          end if
       end do
    end do !species iterator
  end subroutine adv_GCeqn_top
Call graph
adv_gceqn_top calls calculate_sc_p, rad2deg, advance_fpeqn_vars, calculate_sc_e1d, analytical_fields_bmag_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
calculate_sc_e1d calls initialize_sc1d_field_interpolant, mpi_allreduce
initialize_sc1d_field_interpolant calls ezspline_allocated, ezspline_setup, ezspline_error, ezspline_init
include_coulombcollisions_gc_p calls interp_focollision_p, dca_sd, calculate_gcfieldswe_p, analytical_profiles_p, calculate_2dbdbfields_p, calculate_gcfields_p, calculate_gcfields_p_fs, analytical_fields_gc_p, interp_fields_3d_p, add_analytical_e_p, cf_sd, get_random, cb_ee_sd, calculate_gcfields_2x1t_p, cb_ei_sd, interp_fields_p, ca_sd
interp_focollision_p calls ezspline_error, check_if_in_profiles_domain_p, ezspline_interp
dca_sd calls gammacee, vte, psi
calculate_gcfieldswe_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
calculate_2dbdbfields_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_interp
calculate_gcfields_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
calculate_gcfields_p_fs calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
interp_fields_3d_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_interp
cf_sd calls gammacee, vte, psi, clogee, h_j
get_random calls random_get_number_u, omp_get_thread_num
cb_ee_sd calls gammacee, vte, psi, delta
calculate_gcfields_2x1t_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_derivative
cb_ei_sd calls gammacee, vte, g_j, clogei, clogee
interp_fields_p calls ezspline_error, check_if_in_fields_domain_p, ezspline_interp
ca_sd calls gammacee, vte, psi
gammacee calls clogee
clogei calls vte, clog0
delta calls vte
clogee calls vte, clog0
main calls adv_gceqn_top