advance_FP3Deqn_vars – KORC
advance_FP3Deqn_vars Subroutine
30 statements
Source File
public subroutine advance_FP3Deqn_vars(params, X_X, X_Y, X_Z, V_X, V_Y, V_Z, g, m_cache, B0, lam, R0, q0, EF0, B_X, B_Y, B_Z, E_X, E_Y, E_Z, P, F, flagCon, flagCol, PSIp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: X_X
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: X_Y
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: X_Z
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_X
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_Y
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_Z
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: g
real(kind=rp), intent(in) :: m_cache
real(kind=rp), intent(in) :: B0
real(kind=rp), intent(in) :: lam
real(kind=rp), intent(in) :: R0
real(kind=rp), intent(in) :: q0
real(kind=rp), intent(in) :: EF0
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: B_X
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: B_Y
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: B_Z
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: E_X
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: E_Y
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: E_Z
type(PROFILES), intent(in) :: P
type(FIELDS), intent(in) :: F
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCon
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCol
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: PSIp
Calls
Called by
Contents
Source Code
advance_FP3Deqn_vars
Source Code
  subroutine advance_FP3Deqn_vars(params,X_X,X_Y,X_Z,V_X,V_Y,V_Z,g, &
       m_cache,B0,lam,R0,q0,EF0,B_X,B_Y,B_Z,E_X,E_Y,E_Z, &
       P,F,flagCon,flagCol,PSIp)
    TYPE(PROFILES), INTENT(IN)                                 :: P
    TYPE(FIELDS), INTENT(IN)      :: F
    TYPE(KORC_PARAMS), INTENT(INOUT)                              :: params
    !! Core KORC simulation parameters.
    INTEGER                                                    :: cc,pchunk
    !! Chunk iterator.
    INTEGER(ip)                                                    :: tt
    !! time iterator.
    REAL(rp),DIMENSION(params%pchunk), INTENT(IN)  :: X_X,X_Y,X_Z
    REAL(rp),DIMENSION(params%pchunk), INTENT(IN)  :: E_X,E_Y,E_Z,PSIp
    REAL(rp),DIMENSION(params%pchunk), INTENT(IN)  :: B_X,B_Y,B_Z
    INTEGER(is),DIMENSION(params%pchunk), INTENT(INOUT)  :: flagCon,flagCol
    REAL(rp),DIMENSION(params%pchunk) :: U_X,U_Y,U_Z
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: V_X,V_Y,V_Z
    REAL(rp),DIMENSION(params%pchunk),INTENT(INOUT) :: g
    REAL(rp),intent(in) :: B0,EF0,R0,q0,lam,m_cache
    pchunk=params%pchunk
    !    call analytical_fields_p(B0,EF0,R0,q0,lam,X_X,X_Y,X_Z, &
    !         B_X,B_Y,B_Z,E_X,E_Y,E_Z)
    !$OMP SIMD
    !    !$OMP& aligned(U_X,U_Y,U_Z,V_X,V_Y,V_Z,g)
    do cc=1_idef,pchunk
       U_X(cc)=V_X(cc)*g(cc)
       U_Y(cc)=V_Y(cc)*g(cc)
       U_Z(cc)=V_Z(cc)*g(cc)
    end do
    !$OMP END SIMD
    do tt=1_ip,params%t_skip
       call include_CoulombCollisions_FO_p(tt,params,X_X,X_Y,X_Z, &
            U_X,U_Y,U_Z,B_X,B_Y,B_Z,m_cache,P,F,flagCon,flagCol,PSIp)
    end do
    !$OMP SIMD
    !    !$OMP& aligned(U_X,U_Y,U_Z,V_X,V_Y,V_Z,g)
    do cc=1_idef,pchunk
       g(cc)=sqrt(1._rp+U_X(cc)*U_X(cc)+U_Y(cc)*U_Y(cc)+U_Z(cc)*U_Z(cc))
       V_X(cc)=U_X(cc)/g(cc)
       V_Y(cc)=U_Y(cc)/g(cc)
       V_Z(cc)=U_Z(cc)/g(cc)
    end do
    !$OMP END SIMD
  end subroutine advance_FP3Deqn_vars
Call graph
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
include_coulombcollisions_fo_p calls unitvectors_p, analytical_profiles_p, cart_to_cyl_p, cf_sd, interp_focollision_p, dca_sd, cb_ei_sd, get_random, cb_ee_sd, ca_sd
cf_sd calls gammacee, vte, psi, clogee, h_j
interp_focollision_p calls check_if_in_profiles_domain_p, ezspline_interp, ezspline_error
dca_sd calls gammacee, vte, psi
cb_ei_sd calls gammacee, vte, g_j, clogee, clogei
get_random calls random_get_number_u, omp_get_thread_num
cb_ee_sd calls gammacee, vte, psi, delta
ca_sd calls gammacee, vte, psi
gammacee calls clogee
delta calls vte
clogee calls vte, clog0
clogei calls vte, clog0
adv_foeqn_top calls advance_fp3deqn_vars
main calls adv_foeqn_top