advance_FPinterp_vars – KORC
advance_FPinterp_vars Subroutine
15 statements
Source File
public subroutine advance_FPinterp_vars(params, Y_R, Y_PHI, Y_Z, V_PLL, V_MU, m_cache, flagCon, flagCol, F, P, E_PHI, ne, PSIp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: Y_R
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: Y_PHI
real(kind=rp), intent(in), DIMENSION(params%pchunk) :: Y_Z
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_PLL
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_MU
real(kind=rp), intent(in) :: m_cache
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCon
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCol
type(FIELDS), intent(in) :: F
type(PROFILES), intent(in) :: P
real(kind=rp), intent(out), DIMENSION(params%pchunk) :: E_PHI
real(kind=rp), intent(out), DIMENSION(params%pchunk) :: ne
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: PSIp
Calls
Called by
Contents
Source Code
advance_FPinterp_vars
Source Code
  subroutine advance_FPinterp_vars(params,Y_R,Y_PHI,Y_Z,V_PLL,V_MU, &
       m_cache,flagCon,flagCol,F,P,E_PHI,ne,PSIp)
    TYPE(KORC_PARAMS), INTENT(INOUT)                              :: params
    !! Core KORC simulation parameters.
    TYPE(PROFILES), INTENT(IN)                                 :: P
    TYPE(FIELDS), INTENT(IN)                                   :: F
    INTEGER(ip)                                                    :: tt
    !! time iterator.
    REAL(rp),DIMENSION(params%pchunk), INTENT(IN)  :: Y_R,Y_PHI,Y_Z
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: V_PLL,V_MU,PSIp
    REAL(rp),DIMENSION(params%pchunk), INTENT(OUT)  :: E_PHI
    REAL(rp),intent(in) :: m_cache
    INTEGER(is),DIMENSION(params%pchunk),intent(INOUT) :: flagCon,flagCol
    REAL(rp),DIMENSION(params%pchunk), INTENT(OUT) :: ne
    !    write(output_unit_write,'("E_PHI_FP: ",E17.10)') E_PHI
    do tt=1_ip,params%t_skip
       call include_CoulombCollisions_GC_p(tt,params,Y_R,Y_PHI,Y_Z, &
            V_PLL,V_MU,m_cache,flagCon,flagCol,F,P,E_PHI,ne,PSIp)
       !       write(output_unit_write,'("Collision Loop in FP")')
    end do
    !    write(output_unit_write,'("V_PLL: ",E17.10)') V_PLL
    !    write(output_unit_write,'("V_MU: ",E17.10)') V_MU
  end subroutine advance_FPinterp_vars
Call graph
advance_fpinterp_vars calls include_coulombcollisions_gc_p
include_coulombcollisions_gc_p calls interp_fields_3d_p, analytical_profiles_p, add_analytical_e_p, cf_sd, ca_sd, calculate_2dbdbfields_p, calculate_gcfieldswe_p, interp_focollision_p, dca_sd, calculate_gcfields_p, get_random, calculate_gcfields_p_fs, analytical_fields_gc_p, cb_ee_sd, interp_fields_p, cb_ei_sd, calculate_gcfields_2x1t_p
interp_fields_3d_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
cf_sd calls gammacee, vte, psi, clogee, h_j
ca_sd calls gammacee, vte, psi
calculate_2dbdbfields_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
calculate_gcfieldswe_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
interp_focollision_p calls check_if_in_profiles_domain_p, ezspline_interp, ezspline_error
dca_sd calls gammacee, vte, psi
calculate_gcfields_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
get_random calls random_get_number_u, omp_get_thread_num
calculate_gcfields_p_fs calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
cb_ee_sd calls gammacee, vte, psi, delta
interp_fields_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
cb_ei_sd calls gammacee, vte, g_j, clogei, clogee
calculate_gcfields_2x1t_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
gammacee calls clogee
clogei calls vte, clog0
delta calls vte
clogee calls vte, clog0
adv_gcinterp_psi_top calls advance_fpinterp_vars
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_gcinterp_b2d_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top