advance_FPeqn_vars – KORC
advance_FPeqn_vars Subroutine
15 statements
Source File
public subroutine advance_FPeqn_vars(params, Y_R, Y_PHI, Y_Z, V_PLL, V_MU, flagCon, flagCol, m_cache, F, P, PSIp)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_R
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_PHI
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: Y_Z
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_PLL
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: V_MU
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCon
integer(kind=is), intent(inout), DIMENSION(params%pchunk) :: flagCol
real(kind=rp), intent(in) :: m_cache
type(FIELDS), intent(in) :: F
type(PROFILES), intent(in) :: P
real(kind=rp), intent(inout), DIMENSION(params%pchunk) :: PSIp
Calls
Called by
Contents
Source Code
advance_FPeqn_vars
Source Code
  subroutine advance_FPeqn_vars(params,Y_R,Y_PHI,Y_Z,V_PLL,V_MU,flagCon,flagCol, &
       m_cache,F,P,PSIp)
    TYPE(PROFILES), INTENT(IN)                                 :: P
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(INOUT)                              :: params
    !! Core KORC simulation parameters.
    INTEGER(ip)                                                    :: tt
    !! time iterator.
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: Y_R,Y_PHI,Y_Z
    REAL(rp),DIMENSION(params%pchunk), INTENT(INOUT)  :: V_PLL,V_MU,PSIp
    REAL(rp),DIMENSION(params%pchunk)  :: E_PHI
    INTEGER(is),DIMENSION(params%pchunk), INTENT(INOUT)  :: flagCon,flagCol
    REAL(rp),intent(in) :: m_cache
    REAL(rp),DIMENSION(params%pchunk) :: ne
    do tt=1_ip,params%t_skip
       call include_CoulombCollisions_GC_p(tt,params,Y_R,Y_PHI,Y_Z, &
            V_PLL,V_MU,m_cache,flagCon,flagCol,F,P,E_PHI,ne,PSIp)
       !       write(output_unit_write,'("Collision Loop in FP")')
    end do
  end subroutine advance_FPeqn_vars
Call graph
advance_fpeqn_vars calls include_coulombcollisions_gc_p
include_coulombcollisions_gc_p calls interp_fields_3d_p, analytical_profiles_p, add_analytical_e_p, cf_sd, ca_sd, calculate_2dbdbfields_p, calculate_gcfieldswe_p, interp_focollision_p, dca_sd, calculate_gcfields_p, get_random, calculate_gcfields_p_fs, analytical_fields_gc_p, cb_ee_sd, interp_fields_p, cb_ei_sd, calculate_gcfields_2x1t_p
interp_fields_3d_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
cf_sd calls gammacee, vte, psi, clogee, h_j
ca_sd calls gammacee, vte, psi
calculate_2dbdbfields_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
calculate_gcfieldswe_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
interp_focollision_p calls check_if_in_profiles_domain_p, ezspline_interp, ezspline_error
dca_sd calls gammacee, vte, psi
calculate_gcfields_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
get_random calls random_get_number_u, omp_get_thread_num
calculate_gcfields_p_fs calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
cb_ee_sd calls gammacee, vte, psi, delta
interp_fields_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
cb_ei_sd calls gammacee, vte, g_j, clogei, clogee
calculate_gcfields_2x1t_p calls check_if_in_fields_domain_p, ezspline_derivative, ezspline_error
gammacee calls clogee
clogei calls vte, clog0
delta calls vte
clogee calls vte, clog0
adv_gceqn_top calls advance_fpeqn_vars
main calls adv_gceqn_top