assert_eq2 – KORC
assert_eq2 Function
11 statements
Source File
public function assert_eq2(n1, n2, string)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n1
integer, intent(in) :: n2
character(len=*), intent(in) :: string
Return Value integer
Called by
Contents
Source Code
assert_eq2
Source Code
    FUNCTION assert_eq2(n1,n2,string)
    CHARACTER(LEN=*), INTENT(IN) :: string
    INTEGER, INTENT(IN) :: n1,n2
    INTEGER :: assert_eq2
    if (n1 == n2) then
        assert_eq2=n1
    else
        write (*,*) 'nrerror: an assert_eq failed with this tag:', &
            string
        STOP 'program terminated by assert_eq2'
    end if
    END FUNCTION assert_eq2
Call graph
scatter_add_d calls assert_eq2
put_diag_rv calls assert_eq2
get_diag_rv calls assert_eq2
scatter_add_r calls assert_eq2
diagadd_rv calls assert_eq2
diagmult_rv calls assert_eq2
scatter_max_d calls assert_eq2
get_diag_dv calls assert_eq2
assert_eq calls assert_eq2
scatter_max_r calls assert_eq2
diagadd calls diagadd_rv
get_diag calls get_diag_rv, get_diag_dv
scatter_add calls scatter_add_d, scatter_add_r
diagmult calls diagmult_rv
scatter_max calls scatter_max_d, scatter_max_r
put_diag calls put_diag_rv