CB_ei_SD_FIO – KORC
CB_ei_SD_FIO Function
21 statements
Source File
public function CB_ei_SD_FIO(params, v, ne, Te, nimp, Zeff)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: v
real(kind=rp), intent(in) :: ne
real(kind=rp), intent(in) :: Te
real(kind=rp), intent(in), DIMENSION(cparams_ms%num_impurity_species) :: nimp
real(kind=rp), intent(in) :: Zeff
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CB_ei_SD_FIO
Source Code
  function CB_ei_SD_FIO(params,v,ne,Te,nimp,Zeff)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: v
    REAL(rp), INTENT(IN)     :: ne
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp), INTENT(IN)     :: Zeff
    REAL(rp), DIMENSION(cparams_ms%num_impurity_species), INTENT(IN)     :: nimp
    REAL(rp)                 :: CB_ei_SD_FIO
    REAL(rp)                 :: CB_ei_temp
    REAL(rp)                 :: x
    INTEGER :: i
    x = v/VTe(Te)
    CB_ei_SD_FIO  = (0.5_rp*Gammacee(v,ne,Te)/v)* &
         (Zeff*CLogei(v,ne,Te)/CLogee(v,ne,Te))
    if (params%bound_electron_model.eq.'HESSLOW') then
       CB_ei_temp=CB_ei_SD_FIO
       do i=1,cparams_ms%num_impurity_species
          CB_ei_temp=CB_ei_temp+CB_ei_SD_FIO*nimp(i)/(ne* &
               Zeff*CLogei(v,ne,Te))*g_j(i,v)
       end do
       CB_ei_SD_FIO=CB_ei_temp
    end if
  end function CB_ei_SD_FIO
Call graph
cb_ei_sd_fio calls gammacee, vte, g_j, clogee, clogei
gammacee calls clogee
clogee calls vte, clog0
clogei calls vte, clog0
include_coulombcollisions_gcm3dc1_p calls cb_ei_sd_fio
advance_gcinterp_m3dc1_vars calls include_coulombcollisions_gcm3dc1_p