CLogee_wu – KORC
CLogee_wu Function
8 statements
Source File
public function CLogee_wu(params, ne, Te)
With units
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(in) :: ne
ne is in m^-3 and below is converted to cm^-3
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
CLogee_wu
Source Code
  function CLogee_wu(params,ne,Te)
    !! With units
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    REAL(rp), INTENT(IN)     :: ne
    !! ne is in m^-3 and below is converted to cm^-3
    REAL(rp), INTENT(IN)     :: Te ! In Joules
    REAL(rp)                 :: CLogee_wu
    REAL(rp)  :: k=5._rp
    CLogee_wu = CLog0_wu(ne,Te)+ &
         log(1+(2*(params%minimum_particle_g-1)/ &
         (VTe_wu(Te)/C_C)**2)**(k/2._rp))/k
  end function CLogee_wu
Call graph
clogee_wu calls vte_wu, clog0_wu
load_params_ss calls clogee_wu, gammac_wu
gammac_wu calls clogee_wu
initialize_collision_params calls load_params_ss
main calls initialize_collision_params