define_collisions_time_step – KORC
define_collisions_time_step Subroutine
28 statements
Source File
public subroutine define_collisions_time_step(params)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
Calls
Called by
Contents
Source Code
define_collisions_time_step
Source Code
  subroutine define_collisions_time_step(params)
    TYPE(KORC_PARAMS), INTENT(IN)     :: params
    INTEGER(ip)             :: iterations
    REAL(rp)                 :: E
    REAL(rp)                 :: v
    REAL(rp)                 :: Tau
    REAL(rp), DIMENSION(3)         :: nu
    REAL(rp)                 :: num_collisions_in_simulation
    if (params%collisions) then
       E = C_ME*C_C**2 + params%minimum_particle_energy*params%cpp%energy
       v = SQRT(1.0_rp - (C_ME*C_C**2/E)**2)
#ifdef M3D_C1
       nu = (/nu_S_FIO(params,v),nu_D_FIO(params,v),nu_par(v)/)
#else
       nu = (/nu_S(params,v),nu_D(params,v),nu_par(v)/)
#endif
       Tau = MINVAL( 1.0_rp/nu )
!       write(output_unit_write,'("collision freqencies ",F25.12)') nu(3)
!       write(6,*) nu
       cparams_ss%subcycling_iterations = FLOOR(cparams_ss%dTau*Tau/ &
            params%dt,ip) + 1_ip
       num_collisions_in_simulation = params%simulation_time/Tau
       if (params%mpi_params%rank .EQ. 0) then
          write(output_unit_write,'("* * * * * * * * * * * SUBCYCLING FOR  &
               COLLISIONS * * * * * * * * * * *")')
         write(output_unit_write,'("Slowing down freqency (CF): ",E17.10)') &
               nu(1)/params%cpp%time
          write(output_unit_write,'("Pitch angle scattering freqency (CB): ",E17.10)') &
               nu(2)/params%cpp%time
          write(output_unit_write,'("Speed diffusion freqency (CA): ",E17.10)') &
               nu(3)/params%cpp%time
!          write(6,*) Tau
          write(output_unit_write,'("The shorter collisional time in the simulations  &
               is: ",E17.10," s")') Tau*params%cpp%time
          write(output_unit_write,'("Number of KORC iterations per collision: ",I16)')  &
               cparams_ss%subcycling_iterations
          write(output_unit_write,'("Number of collisions in simulated time: ",E17.10)')  &
               num_collisions_in_simulation
          write(output_unit_write,'("* * * * * * * * * * * * * * * * * * * * &
               * * * * * * * * * * * * * * *",/)')
       end if
    end if
  end subroutine define_collisions_time_step
Call graph
define_collisions_time_step calls nu_d_fio, nu_s_fio, nu_d, nu_par, nu_s
nu_d_fio calls cb_ei_fio, cb_ee
nu_s_fio calls cf_fio
nu_d calls cb_ei, cb_ee
nu_par calls ca
nu_s calls cf
cf calls psi, clogee, h_j
cf_fio calls psi, clogee, h_j
ca calls psi
cb_ei_fio calls clogei, g_j, clogee
cb_ei calls clogei, g_j, clogee
cb_ee calls psi
clogei calls vte, clog0
clogee calls vte, clog0
main calls define_collisions_time_step