g_j – KORC
g_j Function
10 statements
Source File
public function g_j(i, v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
real(kind=rp), intent(in) :: v
Return Value real(kind=rp)
Called by
Contents
Source Code
g_j
Source Code
  function g_j(i,v)
    INTEGER, INTENT(IN)     :: i
    REAL(rp), INTENT(IN)     :: v
    REAL(rp)  :: gam
    REAL(rp)  :: p
    REAL(rp)  :: g_j
    gam=1/sqrt(1-v**2)
    p=v*gam
    g_j=2._rp/3._rp*((cparams_ms%Zo(i)**2-cparams_ms%Zj(i)**2)* &
         log((p*cparams_ms%aZj(i))**(3._rp/2._rp)+1)- &
         (cparams_ms%Zo(i)-cparams_ms%Zj(i))**2* &
         (p*cparams_ms%aZj(i))**(3._rp/2._rp)/ &
         ((p*cparams_ms%aZj(i))**(3._rp/2._rp)+1))
!    write(output_unit_write,'("g_j: ",E17.10)') g_j
  end function g_j
Call graph
cb_ei_fio calls g_j
cb_ei calls g_j
cb_ei_sd calls g_j
cb_ei_sd_fio calls g_j
nu_d_fio calls cb_ei_fio
include_coulombcollisions_gcm3dc1_p calls cb_ei_sd_fio
include_coulombcollisions_gc_p calls cb_ei_sd
nu_d calls cb_ei
include_coulombcollisions_fo_p calls cb_ei_sd
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gceqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars calls include_coulombcollisions_gc_p
advance_gcinterp_m3dc1_vars calls include_coulombcollisions_gcm3dc1_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
define_collisions_time_step calls nu_d_fio, nu_d
advance_foeqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_fom3dc1_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psiwe_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls advance_fpinterp_vars
adv_gceqn_top calls advance_fpeqn_vars
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_fointerp_top calls advance_fointerp_vars, advance_fp3dinterp_vars
main calls define_collisions_time_step, adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_fointerp_top, adv_foeqn_top, adv_gcinterp_b2d_top, adv_fom3dc1_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_fom3dc1_top calls advance_fp3dinterp_vars, advance_fom3dc1_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars