get_experimentalG_distribution – KORC
get_experimentalG_distribution Subroutine
10 statements
Source File
public subroutine get_experimentalG_distribution(params, g, eta, go, etao)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: g
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: eta
real(kind=rp), intent(out) :: go
real(kind=rp), intent(out) :: etao
Calls
Contents
Source Code
get_experimentalG_distribution
Source Code
  SUBROUTINE get_experimentalG_distribution(params,g,eta,go,etao)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: g
    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: eta
    REAL(rp), INTENT(OUT) :: go
    REAL(rp), INTENT(OUT) :: etao
    call initialize_params(params)
    call save_params(params)
    call sample_distribution(params,g,eta,go,etao)
  END SUBROUTINE get_experimentalG_distribution
Call graph
get_experimentalg_distribution calls initialize_params, sample_distribution, save_params
initialize_params calls intgamma
sample_distribution calls mpi_barrier, fre, mpi_scatter, random_norm, mpi_bcast
save_params calls h5gclose_f, save_to_hdf5, h5fclose_f
fre calls deg2rad, fgamma
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
intgamma calls fgamma
rsave_to_hdf5 calls h5aclose_f, h5dwrite_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i8save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i4save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i1save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i2save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f