get_fields – KORC
get_fields Subroutine
18 statements
Source File
public subroutine get_fields(params, vars, F)
Note
Inferface with calls to subroutines for calculating the electric and magnetic field for each particle in the simulation.
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
Core KORC simulation parameters.
type(PARTICLES), intent(inout) :: vars
An instance of the KORC derived type PARTICLES.
type(FIELDS), intent(in) :: F
An instance of the KORC derived type FIELDS.
Calls
Called by
Contents
Source Code
get_fields
Source Code
  subroutine get_fields(params,vars,F)
    !! @note Inferface with calls to subroutines for calculating the electric
    !! and magnetic field for each particle in the simulation. @endnote
    TYPE(KORC_PARAMS), INTENT(IN)      :: params
    !! Core KORC simulation parameters.
    TYPE(PARTICLES), INTENT(INOUT)     :: vars
    !!  An instance of the KORC derived type PARTICLES.
    TYPE(FIELDS), INTENT(IN)           :: F
    !! An instance of the KORC derived type FIELDS.
    if (params%field_model(1:10).eq.'ANALYTICAL') then
    !SELECT CASE (TRIM(params%field_model))
    !CASE('ANALYTICAL')
       if (params%field_eval.eq.'eqn') then
          call get_analytical_fields(params,vars, F)
       else
          call interp_fields(params,vars, F)
       end if
    else if (params%field_model(1:8).eq.'EXTERNAL') then
       !       write(output_unit_write,'("2 size of PSI_P: ",I16)') size(vars%PSI_P)
       call interp_fields(params,vars, F)
!       write(output_unit_write,'("get_fields")')
!       write(output_unit_write,'("B_X: ",E17.10)') vars%B(:,1)
!       write(output_unit_write,'("B_Z: ",E17.10)') vars%B(:,2)
!       write(output_unit_write,'("B_Y: ",E17.10)') vars%B(:,3)
       !if (F%Efield.AND..NOT.F%Efield_in_file) then
       !   call analytical_electric_field_cyl(F,vars%Y,vars%E,vars%flagCon)
       !end if
    else if (params%field_model.eq.'M3D_C1') then
       call interp_fields(params,vars, F)
    else if (params%field_model.eq.'UNIFORM') then
       call uniform_fields(vars, F)
    end if
  end subroutine get_fields
Call graph
get_fields calls get_analytical_fields, interp_fields, uniform_fields
get_analytical_fields calls analytical_fields, cart_to_cyl, cart_to_tor_check_if_confined, cyl_check_if_confined, analytical_fields_gc_init, analytical_fields_gc
interp_fields calls gradient_2d_bfields, get_m3d_c1_vector_potential, interp_2d_efields, interp_2d_bfields, get_m3d_c1_electric_fields, interp_3d_bfields, interp_2d_curlbfields, get_m3d_c1_magnetic_fields, interp_3d_efields, calculate_magnetic_field, check_if_in_fields_domain, interp_2d_gradbfields
uniform_fields calls uniform_electric_field, uniform_magnetic_field
gradient_2d_bfields calls ezspline_error
get_m3d_c1_vector_potential calls fio_eval_field
interp_2d_efields calls ezspline_error
interp_2d_bfields calls ezspline_error
get_m3d_c1_electric_fields calls fio_eval_field
interp_3d_bfields calls ezspline_error
interp_2d_curlbfields calls ezspline_error
get_m3d_c1_magnetic_fields calls fio_eval_field, omp_get_thread_num
interp_3d_efields calls ezspline_error
calculate_magnetic_field calls ezspline_error
interp_2d_gradbfields calls ezspline_error
unitvectors calls get_fields
sample_hollmann_distribution_3d_psi calls get_fields
mh_psi calls get_fields
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
gyro_distribution calls unitvectors