get_random – KORC
get_random Function
6 statements
Source File
public function get_random()
Uses
omp_lib
Arguments
None
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
get_random
Source Code
  FUNCTION get_random()
    USE omp_lib
    IMPLICIT NONE
    REAL(rp)            :: get_random
    get_random = random_get_number_U(states(OMP_GET_THREAD_NUM()))
  END FUNCTION get_random
Call graph
get_random calls random_get_number_u, omp_get_thread_num
check_collisions_params calls get_random
include_coulombcollisions_fo_p calls get_random
include_coulombcollisions_gcm3dc1_p calls get_random
include_coulombcollisions_gc_p calls get_random
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_m3dc1_vars calls include_coulombcollisions_gcm3dc1_p
advance_gcinterp_psi_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fom3dc1_vars calls include_coulombcollisions_fo_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gceqn_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psiwe_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls advance_fpinterp_vars
adv_gceqn_top calls advance_fpeqn_vars
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_fointerp_top calls advance_fp3dinterp_vars, advance_fointerp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_fom3dc1_top calls advance_fp3dinterp_vars, advance_fom3dc1_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_fointerp_top, adv_foeqn_top, adv_gcinterp_b2d_top, adv_fom3dc1_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top