get_Avalanche_4D – KORC
get_Avalanche_4D Subroutine
9 statements
Source File
public subroutine get_Avalanche_4D(params, spp, P, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
type(SPECIES), intent(inout) :: spp
type(PROFILES), intent(in) :: P
type(FIELDS), intent(in) :: F
An instance of the KORC derived type FIELDS.
Calls
Contents
Source Code
get_Avalanche_4D
Source Code
  SUBROUTINE get_Avalanche_4D(params,spp,P,F)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    TYPE(SPECIES), INTENT(INOUT)  :: spp
    TYPE(PROFILES), INTENT(IN)    :: P
    TYPE(FIELDS), INTENT(IN)                                   :: F
    !! An instance of the KORC derived type FIELDS.
    call initialize_avalanche_params(params)
    call save_avalanche_params(params)
    call Avalanche_4D(params,spp,P,F)
  END SUBROUTINE get_Avalanche_4D
Call graph
get_avalanche_4d calls initialize_avalanche_params, save_avalanche_params, avalanche_4d
save_avalanche_params calls h5gclose_f, save_to_hdf5, h5fclose_f
avalanche_4d calls mpi_barrier, fre, update_avalanche_params, deg2rad, indicator, random_norm, get_profiles, mpi_scatter, psi_rot
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
get_profiles calls get_analytical_profiles, interp_profiles, cart_to_tor_check_if_confined, cyl_to_cart, cart_to_cyl, uniform_profiles
interp_profiles calls korc_abort, interp_2d_profiles, check_if_in_profiles_domain, interp_3d_profiles, get_m3d_c1_profile
rsave_to_hdf5 calls h5aclose_f, h5dwrite_f, h5tcopy_f, h5awrite_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i8save_to_hdf5 calls h5aclose_f, h5tcopy_f, h5awrite_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i4save_to_hdf5 calls h5aclose_f, h5tcopy_f, h5awrite_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i1save_to_hdf5 calls h5aclose_f, h5tcopy_f, h5awrite_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i2save_to_hdf5 calls h5aclose_f, h5tcopy_f, h5awrite_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
korc_abort calls mpi_barrier, mpi_abort
interp_2d_profiles calls ezspline_error
interp_3d_profiles calls ezspline_error
get_m3d_c1_profile calls fio_eval_field