get_avalanche_distribution – KORC
get_avalanche_distribution Subroutine
10 statements
Source File
public subroutine get_avalanche_distribution(params, g, eta, go, etao)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: g
real(kind=rp), intent(inout), DIMENSION(:), ALLOCATABLE :: eta
real(kind=rp), intent(out) :: go
real(kind=rp), intent(out) :: etao
Calls
Contents
Source Code
get_avalanche_distribution
Source Code
  SUBROUTINE get_avalanche_distribution(params,g,eta,go,etao)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: g
    REAL(rp), DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: eta
    REAL(rp), INTENT(OUT) :: go
    REAL(rp), INTENT(OUT) :: etao
    call initialize_avalanche_params(params)
    call save_avalanche_params(params)
    call sample_distribution(params,g,eta,go,etao)
  END SUBROUTINE get_avalanche_distribution
Call graph
get_avalanche_distribution calls initialize_avalanche_params, save_avalanche_params, sample_distribution
save_avalanche_params calls h5gclose_f, save_to_hdf5, h5fclose_f
sample_distribution calls mpi_barrier, fre, deg2rad, random_norm, mpi_scatter, mpi_bcast
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
rsave_to_hdf5 calls h5aclose_f, h5dwrite_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i8save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i4save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i1save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i2save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f