get_Hollmann_distribution_3D_psi – KORC
get_Hollmann_distribution_3D_psi Subroutine
16 statements
Source File
public subroutine get_Hollmann_distribution_3D_psi(params, spp, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
type(SPECIES), intent(inout) :: spp
type(FIELDS), intent(in) :: F
Calls
Contents
Source Code
get_Hollmann_distribution_3D_psi
Source Code
  SUBROUTINE get_Hollmann_distribution_3D_psi(params,spp,F)
    TYPE(FIELDS), INTENT(IN)                                   :: F
    TYPE(KORC_PARAMS), INTENT(INOUT) :: params
    TYPE(SPECIES),  INTENT(INOUT) :: spp
    INTEGER                 :: mpierr
    if (spp%ppp*params%mpi_params%nmpi.lt.10) then
       if(params%mpi_params%rank.eq.0) then
          write(6,*) 'num_samples need to be atleast 10 but is only: ', &
               spp%ppp*params%mpi_params%nmpi
       end if
       call korc_abort
    end if
    call initialize_Hollmann_params(params)
    call save_Hollmann_params(params)
    call normalize_Hollmann_params(params)
    call sample_Hollmann_distribution_3D_psi(params,spp,F)
  END SUBROUTINE get_Hollmann_distribution_3D_psi
Call graph
get_hollmann_distribution_3d_psi calls korc_abort, save_hollmann_params, initialize_hollmann_params, sample_hollmann_distribution_3d_psi, normalize_hollmann_params
korc_abort calls mpi_barrier, mpi_abort
save_hollmann_params calls h5gclose_f, save_to_hdf5, h5fclose_f
initialize_hollmann_params calls load_data_from_hdf5
sample_hollmann_distribution_3d_psi calls init_random_seed, mpi_barrier, deg2rad, get_random_n, indicator_exp, mpi_scatter, get_fields, fre_h_3d, get_random_u
get_random_n calls random_get_number_n
load_data_from_hdf5 calls h5fclose_f, h5fopen_f, load_array_from_hdf5, load_from_hdf5
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
get_fields calls interp_fields, get_analytical_fields, uniform_fields
fre_h_3d calls deg2rad
get_random_u calls random_get_number_u
load_array_from_hdf5 calls rload_2d_array_from_hdf5, rload_1d_array_from_hdf5, rload_3d_array_from_hdf5
interp_fields calls gradient_2d_bfields, get_m3d_c1_vector_potential, interp_2d_efields, interp_2d_bfields, get_m3d_c1_electric_fields, interp_3d_bfields, interp_2d_curlbfields, get_m3d_c1_magnetic_fields, interp_3d_efields, calculate_magnetic_field, check_if_in_fields_domain, interp_2d_gradbfields
load_from_hdf5 calls iload_from_hdf5, rload_from_hdf5
rsave_to_hdf5 calls h5aclose_f, h5awrite_f, h5dwrite_f, h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5acreate_f, h5tset_size_f
i8save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5acreate_f, h5tset_size_f
get_analytical_fields calls analytical_fields, cart_to_cyl, cart_to_tor_check_if_confined, cyl_check_if_confined, analytical_fields_gc_init, analytical_fields_gc
i4save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5acreate_f, h5tset_size_f
i1save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5acreate_f, h5tset_size_f
uniform_fields calls uniform_electric_field, uniform_magnetic_field
i2save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5sclose_f, h5screate_simple_f, h5dclose_f, h5acreate_f, h5tset_size_f
gradient_2d_bfields calls ezspline_error
get_m3d_c1_vector_potential calls fio_eval_field
interp_2d_efields calls ezspline_error
interp_2d_bfields calls ezspline_error
iload_from_hdf5 calls h5dclose_f, h5dread_f
rload_2d_array_from_hdf5 calls h5dclose_f, h5dread_f
rload_1d_array_from_hdf5 calls h5dclose_f, h5dread_f
get_m3d_c1_electric_fields calls fio_eval_field
interp_3d_bfields calls ezspline_error
interp_2d_curlbfields calls ezspline_error
get_m3d_c1_magnetic_fields calls fio_eval_field, omp_get_thread_num
rload_3d_array_from_hdf5 calls h5dclose_f, h5dread_f
rload_from_hdf5 calls h5dclose_f, h5dread_f
interp_3d_efields calls ezspline_error
calculate_magnetic_field calls ezspline_error
interp_2d_gradbfields calls ezspline_error