get_random_U – KORC
get_random_U Function
6 statements
Source File
public function get_random_U()
Uses
omp_lib
Arguments
None
Return Value real(kind=rp)
Calls
Called by
Contents
Source Code
get_random_U
Source Code
  FUNCTION get_random_U()
    USE omp_lib
    IMPLICIT NONE
    REAL(rp)            :: get_random_U
    get_random_U = random_get_number_U(state)
  END FUNCTION get_random_U
Call graph
get_random_u calls random_get_number_u
mh_psi calls get_random_u
sample_hollmann_distribution_3d_psi calls get_random_u
sample_hollmann_distribution_3d calls get_random_u
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
get_hollmann_distribution_3d calls sample_hollmann_distribution_3d