initialize_korc_parameters – KORC
initialize_korc_parameters Subroutine
9 statements
Source File
public subroutine initialize_korc_parameters(params)
Note
Interface for calling initialization subroutines
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Core KORC simulation parameters.
Calls
Called by
Contents
Source Code
initialize_korc_parameters
Source Code
  subroutine initialize_korc_parameters(params)
    !! @note Interface for calling initialization subroutines @endnote
    TYPE(KORC_PARAMS), INTENT(INOUT)     :: params
    !! Core KORC simulation parameters.
    INTEGER                             :: mpierr
    !! MPI error status.
    call MPI_BARRIER(MPI_COMM_WORLD,mpierr)
    call read_namelist(params,params%path_to_inputs,.true.,params%path_to_outputs)
    call MPI_BARRIER(MPI_COMM_WORLD,mpierr)
    call load_korc_params(params)
    call MPI_BARRIER(MPI_COMM_WORLD,mpierr)
  end subroutine initialize_korc_parameters
Call graph
initialize_korc_parameters calls load_korc_params, read_namelist, mpi_barrier
read_namelist calls mpi_barrier, korc_abort, rmcoment
korc_abort calls mpi_barrier, mpi_abort
main calls initialize_korc_parameters