initialize_communications – KORC
initialize_communications Subroutine
16 statements
Source File
public subroutine initialize_communications(params)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
Calls
Called by
Contents
Source Code
initialize_communications
Source Code
  subroutine initialize_communications(params)
    TYPE(KORC_PARAMS), INTENT(INOUT)     :: params
    CHARACTER(MAX_STRING_LENGTH)         :: string
    call initialize_mpi(params)
    !$OMP PARALLEL SHARED(params)
    params%num_omp_threads = OMP_GET_NUM_THREADS()
    !$OMP END PARALLEL
    if (params%mpi_params%rank.EQ.0) then
       write(output_unit_write,'(/,"* * * * * * * OMP SET-UP * * * * * * *")')
       !$OMP PARALLEL
       !$OMP MASTER
       write(output_unit_write,'(/,"OMP threads per MPI process: ",I3)') OMP_GET_NUM_THREADS()
       write(output_unit_write,'(/,"Cores available per MPI process: ",I3)') OMP_GET_NUM_PROCS()
       !$OMP END MASTER
       !$OMP END PARALLEL
#ifdef GNU
       call GET_ENVIRONMENT_VARIABLE("OMP_PLACES",string)
       write(output_unit_write,'(/,"OMP places: ",A30)') TRIM(string)
       call GET_ENVIRONMENT_VARIABLE("GOMP_CPU_AFFINITY",string)
       write(output_unit_write,'(/,"OMP CPU affinity: ",A30)') TRIM(string)
#endif
       write(output_unit_write,'("* * * * * * * * * * * *  * * * * * * *",/)')
    end if
  end subroutine initialize_communications
Call graph
initialize_communications calls initialize_mpi, omp_get_num_threads, omp_get_num_procs
initialize_mpi calls mpi_init, mpi_cart_create, mpi_barrier, mpi_comm_size, mpi_reduce, mpi_comm_rank, mpi_abort, mpi_initialized, set_paths, mpi_bcast
set_paths calls korc_abort
korc_abort calls mpi_barrier, mpi_abort
main calls initialize_communications