initialize_collision_params – KORC
initialize_collision_params Subroutine
40 statements
Source File
public subroutine initialize_collision_params(params, spp, P, F)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(inout) :: params
type(SPECIES), intent(inout), DIMENSION(:), ALLOCATABLE :: spp
type(PROFILES), intent(inout) :: P
type(FIELDS), intent(in) :: F
Calls
Called by
Contents
Source Code
initialize_collision_params
Source Code
  subroutine initialize_collision_params(params,spp,P,F)
    TYPE(KORC_PARAMS), INTENT(INOUT) :: params
    TYPE(SPECIES), DIMENSION(:), ALLOCATABLE, INTENT(INOUT)       :: spp
    TYPE(PROFILES), INTENT(INOUT)  :: P
    TYPE(FIELDS), INTENT(IN)                :: F
    INTEGER                                            :: ii
    if (params%collisions.or.((params%field_model.eq.'M3D_C1').and. &
         params%radiation)) then
       if (params%mpi_params%rank .EQ. 0) then
          write(output_unit_write,'(/,"* * * * * * * INITIALIZING COLLISIONS * * * * * * *")')
       end if
       SELECT CASE (TRIM(params%collisions_model))
       CASE (MODEL1)
          call load_params_ss(params)
          SELECT CASE(TRIM(params%bound_electron_model))
          CASE ('NO_BOUND')
             call load_params_ms(params)
          CASE('HESSLOW')
             call load_params_ms(params)
          CASE('ROSENBLUTH')
             call load_params_ms(params)
          CASE DEFAULT
             write(output_unit_write,'("Default case")')
          END SELECT
          do ii=1_idef,params%num_species
             ALLOCATE( spp(ii)%vars%nimp(spp(ii)%ppp, &
                  cparams_ms%num_impurity_species) )
             spp(ii)%vars%nimp = 0.0_rp
          end do
#ifdef M3D_C1
          if (TRIM(params%field_model) .eq. 'M3D_C1') then
             call initialize_m3d_c1_imp(params,F,P, &
                  cparams_ms%num_impurity_species,.true.)
          endif
#endif
       CASE (MODEL2)
          call load_params_ms(params)
       CASE DEFAULT
          write(output_unit_write,'("Default case")')
       END SELECT
       if (params%mpi_params%rank .EQ. 0) then
          write(output_unit_write,'("* * * * * * * * * * * * * * * * * * * * * * * * * *",/)')
       end if
    end if
  end subroutine initialize_collision_params
Call graph
initialize_collision_params calls load_params_ss, load_params_ms, initialize_m3d_c1_imp
load_params_ss calls clogei_wu, gammac_wu, vte_wu, clogee_wu
load_params_ms calls zj_mult, zo_mult
initialize_m3d_c1_imp calls fio_make_species, fio_get_field, fio_open_source, fio_set_int_option, fio_get_options
clogei_wu calls vte_wu, clog0_wu
gammac_wu calls clogee_wu
clogee_wu calls vte_wu, clog0_wu
main calls initialize_collision_params