interp_fields_3D_p – KORC
interp_fields_3D_p Subroutine
15 statements
Source File
public subroutine interp_fields_3D_p(pchunk, F, Y_R, Y_PHI, Y_Z, B_R, B_PHI, B_Z, E_R, E_PHI, E_Z, curlB_R, curlB_PHI, curlB_Z, gradB_R, gradB_PHI, gradB_Z, flag_cache)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: pchunk
type(FIELDS), intent(in) :: F
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_R
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_PHI
real(kind=rp), intent(in), DIMENSION(pchunk) :: Y_Z
real(kind=rp), intent(out), DIMENSION(pchunk) :: B_R
real(kind=rp), intent(out), DIMENSION(pchunk) :: B_PHI
real(kind=rp), intent(out), DIMENSION(pchunk) :: B_Z
real(kind=rp), intent(out), DIMENSION(pchunk) :: E_R
real(kind=rp), intent(out), DIMENSION(pchunk) :: E_PHI
real(kind=rp), intent(out), DIMENSION(pchunk) :: E_Z
real(kind=rp), intent(out), DIMENSION(pchunk) :: curlB_R
real(kind=rp), intent(out), DIMENSION(pchunk) :: curlB_PHI
real(kind=rp), intent(out), DIMENSION(pchunk) :: curlB_Z
real(kind=rp), intent(out), DIMENSION(pchunk) :: gradB_R
real(kind=rp), intent(out), DIMENSION(pchunk) :: gradB_PHI
real(kind=rp), intent(out), DIMENSION(pchunk) :: gradB_Z
integer(kind=is), intent(inout), DIMENSION(pchunk) :: flag_cache
Calls
Called by
Contents
Source Code
interp_fields_3D_p
Source Code
subroutine interp_fields_3D_p(pchunk,F,Y_R,Y_PHI,Y_Z,B_R,B_PHI,B_Z,E_R,E_PHI,E_Z, &
     curlb_R,curlb_PHI,curlb_Z,gradB_R,gradB_PHI,gradB_Z,flag_cache)
  INTEGER, INTENT(IN)  :: pchunk
  TYPE(FIELDS), INTENT(IN)                               :: F
  REAL(rp),DIMENSION(pchunk),INTENT(IN)   :: Y_R,Y_PHI,Y_Z
  REAL(rp),DIMENSION(pchunk),INTENT(OUT)   :: B_R,B_PHI,B_Z
  REAL(rp),DIMENSION(pchunk),INTENT(OUT)   :: gradB_R,gradB_PHI,gradB_Z
  REAL(rp),DIMENSION(pchunk),INTENT(OUT)   :: curlB_R,curlB_PHI,curlB_Z
  REAL(rp),DIMENSION(pchunk),INTENT(OUT)   :: E_R,E_PHI,E_Z
  INTEGER(is),DIMENSION(pchunk),INTENT(INOUT)   :: flag_cache
  REAL(rp), DIMENSION(pchunk)     :: Y_PHI_mod
  Y_PHI_mod=modulo(Y_PHI,2._rp*C_PI)
!  write(output_unit_write,*) Y_PHI(1)
!  write(output_unit_write,*) Y_PHI_mod(1)
  call check_if_in_fields_domain_p(pchunk,F,Y_R,Y_PHI_mod,Y_Z,flag_cache)
  call EZspline_interp(bfield_3d%R,bfield_3d%PHI,bfield_3d%Z,efield_3d%R, &
       efield_3d%PHI,efield_3d%Z,gradB_3d%R,gradB_3d%PHI,gradB_3d%Z, &
       curlb_3d%R,curlb_3d%PHI,curlb_3d%Z,pchunk,Y_R,Y_PHI_mod,Y_Z,B_R,B_PHI,B_Z, &
       E_R,E_PHI,E_Z,gradB_R,gradB_PHI,gradB_Z,curlb_R,curlb_PHI,curlb_Z, &
       ezerr)
  call EZspline_error(ezerr)
end subroutine interp_fields_3D_p
Call graph
interp_fields_3d_p calls check_if_in_fields_domain_p, ezspline_interp, ezspline_error
advance_gcinterp_b_vars calls interp_fields_3d_p, include_coulombcollisions_gc_p
include_coulombcollisions_gc_p calls interp_fields_3d_p
advance_gcinterp_psi_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_gceqn_vars calls include_coulombcollisions_gc_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psiwe_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls advance_fpinterp_vars
adv_gceqn_top calls advance_fpeqn_vars
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_gcinterp_b2d_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, adv_gcinterp_psi_top_fs, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top