korc_abort – KORC
korc_abort Subroutine
5 statements
Source File
public subroutine korc_abort()
Note
Subroutine that terminates the simulation.
Arguments
None
Calls
Called by
Contents
Source Code
korc_abort
Source Code
  subroutine korc_abort()
    !! @note Subroutine that terminates the simulation. @endnote
    INTEGER :: mpierr
    !! MPI error status
    call MPI_BARRIER(MPI_COMM_WORLD,mpierr)
    call MPI_ABORT(MPI_COMM_WORLD, -2000, mpierr)
  end subroutine korc_abort
Call graph
korc_abort calls mpi_barrier, mpi_abort
get_hollmann_distribution_3d calls korc_abort
interp_profiles calls korc_abort
initialize_fields calls korc_abort
get_hollmann_distribution_3d_psi calls korc_abort
load_particles_ic calls korc_abort
mean_f_field calls korc_abort
read_namelist calls korc_abort
set_paths calls korc_abort
intitial_spatial_distribution calls korc_abort
get_hollmann_distribution calls korc_abort
initialize_korc_parameters calls read_namelist
set_up_particles_ic calls load_particles_ic, intitial_spatial_distribution
main calls initialize_fields, initialize_korc_parameters, set_up_particles_ic, initialize_communications
initialize_mpi calls set_paths
get_profiles calls interp_profiles
avalanche_4d calls get_profiles
initialize_communications calls initialize_mpi
get_avalanche_4d calls avalanche_4d