rsave_1d_array_to_hdf5 – KORC
rsave_1d_array_to_hdf5 Subroutine
56 statements
Source File
private subroutine rsave_1d_array_to_hdf5(h5file_id, dset, rdata, attr)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: h5file_id
character(len=MAX_STRING_LENGTH), intent(in) :: dset
real(kind=rp), intent(in), DIMENSION(:) :: rdata
character(len=MAX_STRING_LENGTH), intent(in), optional DIMENSION(:), ALLOCATABLE :: attr
Calls
Called by
Contents
Source Code
rsave_1d_array_to_hdf5
Source Code
  subroutine rsave_1d_array_to_hdf5(h5file_id,dset,rdata,attr)
    INTEGER(HID_T), INTENT(IN)                                                         :: h5file_id
    CHARACTER(MAX_STRING_LENGTH), INTENT(IN)                                         :: dset
    REAL(rp), DIMENSION(:), INTENT(IN)                                                 :: rdata
    CHARACTER(MAX_STRING_LENGTH), OPTIONAL, DIMENSION(:), ALLOCATABLE, INTENT(IN)     :: attr
    CHARACTER(4)                                                                     :: aname = "Info"
    INTEGER(HID_T)                                                                     :: dset_id
    INTEGER(HID_T)                                                                     :: dspace_id
    INTEGER(HID_T)                                                                     :: aspace_id
    INTEGER(HID_T)                                                                     :: attr_id
    INTEGER(HID_T)                                                                     :: atype_id
    INTEGER(HSIZE_T), DIMENSION(:), ALLOCATABLE                                     :: dims
    INTEGER(HSIZE_T), DIMENSION(:), ALLOCATABLE                                     :: adims
    INTEGER                                                                         :: rank
    INTEGER                                                                         :: arank
    INTEGER(SIZE_T)                                                                 :: tmplen
    INTEGER(SIZE_T)                                                                 :: attrlen
    INTEGER                                                                         :: h5error
    INTEGER                                                                         :: rr,dd
    rank = size(shape(rdata))
    ALLOCATE(dims(rank))
    dims = shape(rdata)
    ! * * * Write data to file * * *
    call h5screate_simple_f(rank,dims,dspace_id,h5error)
    call h5dcreate_f(h5file_id, TRIM(dset), KORC_HDF5_REAL, dspace_id, dset_id, h5error)
    if (rp .EQ. INT(rp_hdf5)) then
       call h5dwrite_f(dset_id, KORC_HDF5_REAL, rdata, dims, h5error)
    else
       call h5dwrite_f(dset_id, KORC_HDF5_REAL, REAL(rdata,4), dims, h5error)
    end if
    if (PRESENT(attr)) then
       arank = size(shape(attr))
       ALLOCATE(adims(arank))
       adims = shape(attr)
       ! * * * Write attribute of data to file * * *
       tmplen = 0
       attrlen = 0
       do rr=1_idef,arank
          do dd=1_idef,adims(rr)
             tmplen = LEN_TRIM(attr(dd))
             if ( tmplen .GT. attrlen) then
                attrlen = tmplen
             end if
          end do
       end do
       call h5screate_simple_f(arank,adims,aspace_id,h5error)
       call h5tcopy_f(H5T_NATIVE_CHARACTER, atype_id, h5error)
       call h5tset_size_f(atype_id, attrlen, h5error)
       call h5acreate_f(dset_id, aname, atype_id, aspace_id, attr_id, h5error)
       call h5awrite_f(attr_id, atype_id, attr, adims, h5error)
       call h5aclose_f(attr_id, h5error)
       call h5sclose_f(aspace_id, h5error)
       ! * * * Write attribute of data to file * * *
       DEALLOCATE(adims)
    end if
    call h5sclose_f(dspace_id, h5error)
    call h5dclose_f(dset_id, h5error)
    ! * * * Write data to file * * *
    DEALLOCATE(dims)
  end subroutine rsave_1d_array_to_hdf5
Call graph
rsave_1d_array_to_hdf5 calls h5aclose_f, h5dwrite_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
save_array_to_hdf5 calls rsave_1d_array_to_hdf5
save_1d_array_to_hdf5 calls rsave_1d_array_to_hdf5
save_simulation_parameters calls save_1d_array_to_hdf5
save_restart_variables calls save_1d_array_to_hdf5
save_simulation_outputs calls save_1d_array_to_hdf5
save_params_ms calls save_1d_array_to_hdf5
save_collision_params calls save_params_ms
main calls save_simulation_parameters, save_restart_variables, save_simulation_outputs, save_collision_params