save_collision_params – KORC
save_collision_params Subroutine
25 statements
Source File
public subroutine save_collision_params(params)
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
Calls
Called by
Contents
Source Code
save_collision_params
Source Code
  subroutine save_collision_params(params)
    TYPE(KORC_PARAMS), INTENT(IN) :: params
    if (.NOT.(params%restart.OR.params%proceed)) then
       if (params%collisions) then
          SELECT CASE (TRIM(params%collisions_model))
          CASE (MODEL1)
             call save_params_ss(params)
             SELECT CASE(TRIM(params%bound_electron_model))
             CASE ('NO_BOUND')
                call save_params_ms(params)
             CASE('HESSLOW')
                call save_params_ms(params)
             CASE('ROSENBLUTH')
                call save_params_ms(params)
             CASE DEFAULT
                write(output_unit_write,'("Default case")')
             END SELECT
          CASE (MODEL2)
             call save_params_ms(params)
          CASE DEFAULT
             write(output_unit_write,'("Default case")')
          END SELECT
       end if
    end if
  end subroutine save_collision_params
Call graph
save_collision_params calls save_params_ss, save_params_ms
save_params_ss calls save_string_parameter, h5gclose_f, save_to_hdf5, h5fclose_f
save_params_ms calls save_string_parameter, h5gclose_f, save_to_hdf5, save_1d_array_to_hdf5, h5fclose_f
save_string_parameter calls h5tset_strpad_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5dwrite_vl_f
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
save_1d_array_to_hdf5 calls rsave_1d_array_to_hdf5, isave_1d_array_to_hdf5
rsave_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5dwrite_f, h5awrite_f, h5acreate_f, h5tset_size_f
i8save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
i4save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
i1save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
rsave_1d_array_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5dwrite_f, h5awrite_f, h5acreate_f, h5tset_size_f
i2save_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5awrite_f, h5acreate_f, h5tset_size_f
isave_1d_array_to_hdf5 calls h5tcopy_f, h5screate_simple_f, h5sclose_f, h5dclose_f, h5aclose_f, h5dwrite_f, h5awrite_f, h5acreate_f, h5tset_size_f
main calls save_collision_params