save_gamma_params – KORC
save_gamma_params Subroutine
40 statements
Source File
private subroutine save_gamma_params(params)
@brief Surboutine that saves the Gamma distribution parameters to the HDF5 file gamma_distribution_parameters.h5.
@param[in] params Core KORC simulation parameters. @param filename String containing the name of the HDF5 file. @param gname String containing the group name of a set of KORC parameters. @param attr_array An 1-D array with attributes of 1-D real or integer arrays that are passed to KORC interfaces of HDF5 I/O subroutines. @param dset Name of data set to be saved to file. @param attr A single attributes of real or integer data that is passed to KORC interfaces of HDF5 I/O subroutines. @param h5file_id HDF5 file identifier. @param group_id HDF5 group identifier. @param h5error HDF5 error status. @param units Temporary variable used to add physical units to KORC parameters.
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
Calls
Called by
Contents
Source Code
save_gamma_params
Source Code
  SUBROUTINE save_gamma_params(params)
    TYPE(KORC_PARAMS), INTENT(IN)                             :: params
    CHARACTER(MAX_STRING_LENGTH)                             :: filename
    CHARACTER(MAX_STRING_LENGTH)                             :: gname
    CHARACTER(MAX_STRING_LENGTH), DIMENSION(:), ALLOCATABLE :: attr_array
    CHARACTER(MAX_STRING_LENGTH)                             :: dset
    CHARACTER(MAX_STRING_LENGTH)                             :: attr
    INTEGER(HID_T)                                             :: h5file_id
    INTEGER(HID_T)                                             :: group_id
    INTEGER                                                 :: h5error
    REAL(rp)                                                 :: units
    if (params%mpi_params%rank .EQ. 0) then
       filename = TRIM(params%path_to_outputs) // "gamma_distribution_parameters.h5"
       call h5fcreate_f(TRIM(filename), H5F_ACC_TRUNC_F, h5file_id, h5error)
       gname = "params"
       call h5gcreate_f(h5file_id, TRIM(gname), group_id, h5error)
       dset = TRIM(gname) // "/min_energy"
       attr = "Minimum energy in avalanche PDF (eV)"
       units = 1.0_rp/C_E
       call save_to_hdf5(h5file_id,dset,units*gamma_pdf_params%min_energy,attr)
       dset = TRIM(gname) // "/max_energy"
       attr = "Maximum energy in avalanche PDF (eV)"
       units = 1.0_rp/C_E
       call save_to_hdf5(h5file_id,dset,units*gamma_pdf_params%max_energy,attr)
       dset = TRIM(gname) // "/max_p"
       attr = "Maximum momentum in avalanche PDF (me*c^2)"
       call save_to_hdf5(h5file_id,dset,gamma_pdf_params%max_p,attr)
       dset = TRIM(gname) // "/min_p"
       attr = "Maximum momentum in avalanche PDF (me*c^2)"
       call save_to_hdf5(h5file_id,dset,gamma_pdf_params%min_p,attr)
       dset = TRIM(gname) // "/k"
       attr = "Shape factor"
       call save_to_hdf5(h5file_id,dset,gamma_pdf_params%k,attr)
       dset = TRIM(gname) // "/t"
       attr = "Scale factor"
       call save_to_hdf5(h5file_id,dset,gamma_pdf_params%t,attr)
       call h5gclose_f(group_id, h5error)
       call h5fclose_f(h5file_id, h5error)
    end if
  END SUBROUTINE save_gamma_params
Call graph
save_gamma_params calls save_to_hdf5, h5fclose_f, h5gclose_f
save_to_hdf5 calls rsave_to_hdf5, i8save_to_hdf5, i4save_to_hdf5, i1save_to_hdf5, i2save_to_hdf5
rsave_to_hdf5 calls h5aclose_f, h5dwrite_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i8save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i4save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i1save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
i2save_to_hdf5 calls h5aclose_f, h5awrite_f, h5tcopy_f, h5screate_simple_f, h5sclose_f, h5acreate_f, h5tset_size_f, h5dclose_f
get_gamma_distribution calls save_gamma_params