unitVectors – KORC
unitVectors Subroutine
54 statements
Source File
public subroutine unitVectors(params, Xo, F, b1, b2, b3, flag, cart, hint)
Note
Subrotuine that calculates an orthonormal basis using information of the (local) magnetic field at position .
Arguments
Type Intent Optional Attributes Name
type(KORC_PARAMS), intent(in) :: params
Core KORC simulation parameters.
real(kind=rp), intent(in), DIMENSION(:,:), ALLOCATABLE :: Xo
Array with the position of the simulated particles.
type(FIELDS), intent(in) :: F
F An instance of the KORC derived type FIELDS.
real(kind=rp), intent(inout), DIMENSION(:,:), ALLOCATABLE :: b1
Basis vector pointing along the local magnetic field, that is, along .
real(kind=rp), intent(inout), DIMENSION(:,:), ALLOCATABLE :: b2
Basis vector perpendicular to b1
real(kind=rp), intent(inout), DIMENSION(:,:), ALLOCATABLE :: b3
Basis vector perpendicular to b1 and b2.
integer(kind=is), intent(inout), optional DIMENSION(:), ALLOCATABLE :: flag
Flag for each particle to decide whether it is being followed (flag=T) or not (flag=F).
logical :: cart
type(C_PTR), intent(inout), DIMENSION(:), ALLOCATABLE :: hint
Flag for each particle to decide whether it is being followed (flag=T) or not (flag=F).
Calls
Called by
Contents
Source Code
unitVectors
Source Code
  subroutine unitVectors(params,Xo,F,b1,b2,b3,flag,cart,hint)
    !! @note Subrotuine that calculates an orthonormal basis using information
    !! of the (local) magnetic field at position \(\mathbf{X}_0\). @endnote
    TYPE(KORC_PARAMS), INTENT(IN)                                      :: params
    !! Core KORC simulation parameters.
    REAL(rp), DIMENSION(:,:), ALLOCATABLE, INTENT(IN)                  :: Xo
    !! Array with the position of the simulated particles.
    TYPE(FIELDS), INTENT(IN)                                           :: F
    !! F An instance of the KORC derived type FIELDS.
    REAL(rp), DIMENSION(:,:), ALLOCATABLE, INTENT(INOUT)               :: b1
    !! Basis vector pointing along the local magnetic field,
    !! that is, along \(\mathbf{b} = \mathbf{B}/B\).
    REAL(rp), DIMENSION(:,:), ALLOCATABLE, INTENT(INOUT)               :: b2
    !!  Basis vector perpendicular to b1
    REAL(rp), DIMENSION(:,:), ALLOCATABLE, INTENT(INOUT)               :: b3
    !! Basis vector perpendicular to b1 and b2.
    INTEGER(is), DIMENSION(:), ALLOCATABLE, OPTIONAL, INTENT(INOUT)    :: flag
    !! Flag for each particle to decide whether it is being
    !! followed (flag=T) or not (flag=F).
    TYPE(C_PTR), DIMENSION(:), ALLOCATABLE, INTENT(INOUT)    :: hint
    !! Flag for each particle to decide whether it is being
    !! followed (flag=T) or not (flag=F).
    TYPE(PARTICLES)                                                    :: vars
    !! A temporary instance of the KORC derived type PARTICLES.
    INTEGER                                                            :: ii
    !! Iterator.
    INTEGER                                                            :: ppp
    !! Number of particles.
    LOGICAL :: cart
!    write(output_unit_write,*) 'in unitVector'
    ppp = SIZE(Xo,1) ! Number of particles
    ALLOCATE( vars%X(ppp,3) )
    ALLOCATE( vars%Y(ppp,3) )
    ALLOCATE( vars%B(ppp,3) )
    ALLOCATE( vars%gradB(ppp,3) )
    ALLOCATE( vars%curlb(ppp,3) )
    ALLOCATE( vars%PSI_P(ppp) )
    ALLOCATE( vars%E(ppp,3) )
    ALLOCATE( vars%flagCon(ppp) )
    ALLOCATE( vars%hint(ppp) )
    vars%X = Xo
    vars%hint = hint
    vars%flagCon = 1_idef
    vars%B=0._rp
    vars%PSI_P=0._rp
    vars%cart=.false.
    !write(output_unit_write,*) 'before init_random_seed'
    call init_random_seed()
   ! write(output_unit_write,*) 'before get_fields'
    !write(6,*) 'before first get fields'
    call get_fields(params,vars,F)
    !write(6,*) 'before second get fields'
    !    write(output_unit_write,'("Bx: ",E17.10)') vars%B(:,1)
    !    write(output_unit_write,'("By: ",E17.10)') vars%B(:,2)
    !    write(output_unit_write,'("Bz: ",E17.10)') vars%B(:,3)
    !write(output_unit_write,*) 'before b1,b2,b3 calculation'
    do ii=1_idef,ppp
       if ( vars%flagCon(ii) .EQ. 1_idef ) then
          b1(ii,:) = vars%B(ii,:)/sqrt(vars%B(ii,1)*vars%B(ii,1)+ &
               vars%B(ii,2)*vars%B(ii,2)+vars%B(ii,3)*vars%B(ii,3))
          b2(ii,:) = cross(b1(ii,:),(/0.0_rp,0.0_rp,1.0_rp/))
          b2(ii,:) = b2(ii,:)/sqrt(b2(ii,1)*b2(ii,1)+b2(ii,2)*b2(ii,2)+ &
               b2(ii,3)*b2(ii,3))
          b3(ii,:) = cross(b1(ii,:),b2(ii,:))
          b3(ii,:) = b3(ii,:)/sqrt(b3(ii,1)*b3(ii,1)+b3(ii,2)*b3(ii,2)+ &
               b3(ii,3)*b3(ii,3))
       end if
    end do
    !write(output_unit_write,*) 'before copying hint and flag'
    hint = vars%hint
    if (PRESENT(flag)) then
       flag = vars%flagCon
    end if
    DEALLOCATE( vars%X )
    DEALLOCATE( vars%Y )
    DEALLOCATE( vars%B )
    DEALLOCATE( vars%PSI_P )
    DEALLOCATE( vars%gradB )
    DEALLOCATE( vars%curlb )
    DEALLOCATE( vars%E )
    DEALLOCATE( vars%flagCon )
    DEALLOCATE( vars%hint)
    !write(output_unit_write,*) 'out unitVectors'
  end subroutine unitVectors
Call graph
unitvectors calls get_fields, init_random_seed, cross
get_fields calls get_analytical_fields, interp_fields, uniform_fields
get_analytical_fields calls analytical_fields, cart_to_cyl, cart_to_tor_check_if_confined, cyl_check_if_confined, analytical_fields_gc_init, analytical_fields_gc
interp_fields calls gradient_2d_bfields, get_m3d_c1_vector_potential, interp_2d_efields, interp_2d_bfields, get_m3d_c1_electric_fields, interp_3d_bfields, interp_2d_curlbfields, get_m3d_c1_magnetic_fields, interp_3d_efields, calculate_magnetic_field, check_if_in_fields_domain, interp_2d_gradbfields
uniform_fields calls uniform_electric_field, uniform_magnetic_field
gradient_2d_bfields calls ezspline_error
get_m3d_c1_vector_potential calls fio_eval_field
interp_2d_efields calls ezspline_error
interp_2d_bfields calls ezspline_error
get_m3d_c1_electric_fields calls fio_eval_field
interp_3d_bfields calls ezspline_error
interp_2d_curlbfields calls ezspline_error
get_m3d_c1_magnetic_fields calls fio_eval_field, omp_get_thread_num
interp_3d_efields calls ezspline_error
calculate_magnetic_field calls ezspline_error
interp_2d_gradbfields calls ezspline_error
gyro_distribution calls unitvectors