VTe – KORC
VTe Function
5 statements
Source File
private function VTe(Te)
Dimensionless temperature
Arguments
Type Intent Optional Attributes Name
real(kind=rp), intent(in) :: Te
Return Value real(kind=rp)
Called by
Contents
Source Code
VTe
Source Code
  function VTe(Te)
    !! Dimensionless temperature
    REAL(rp), INTENT(IN)     :: Te
    REAL(rp)                 :: VTe
    VTe = SQRT(2.0_rp*Te)*cparams_ss%VTeo
  end function VTe
Call graph
cf_sd calls vte, clogee, gammacee
cb_ei_sd_fio calls vte, clogee, clogei, gammacee
delta calls vte
dca_sd calls vte, gammacee
cb_ei_sd calls vte, clogee, clogei, gammacee
cf_sd_fio calls vte, clogee, gammacee
cb_ee_sd calls vte, delta, gammacee
clogee calls vte
ca_sd calls vte, gammacee
clogei calls vte
cf calls clogee
cf_fio calls clogee
gammacee calls clogee
include_coulombcollisions_gcm3dc1_p calls cb_ei_sd_fio, dca_sd, cf_sd_fio, cb_ee_sd, ca_sd
include_coulombcollisions_gc_p calls cf_sd, dca_sd, cb_ei_sd, cb_ee_sd, ca_sd
cb_ei_fio calls clogee, clogei
cb_ei calls clogee, clogei
include_coulombcollisions_fo_p calls cf_sd, dca_sd, cb_ei_sd, cb_ee_sd, ca_sd
advance_fp3deqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_2dbdb_vars calls include_coulombcollisions_gc_p
advance_fpinterp_vars calls include_coulombcollisions_gc_p
advance_gcinterp_psi_vars_fs calls include_coulombcollisions_gc_p
advance_fointerp_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb1_vars calls include_coulombcollisions_gc_p
advance_gcinterp_3dbdb_vars calls include_coulombcollisions_gc_p
nu_s_fio calls cf_fio
advance_fp3dinterp_vars calls include_coulombcollisions_fo_p
advance_fpeqn_vars calls include_coulombcollisions_gc_p
advance_gceqn_vars calls include_coulombcollisions_gc_p
nu_s calls cf
advance_gcinterp_psi_vars calls include_coulombcollisions_gc_p
advance_gcinterp_m3dc1_vars calls include_coulombcollisions_gcm3dc1_p
advance_gcinterp_psi2x1t_vars calls include_coulombcollisions_gc_p
advance_foeqn_vars calls include_coulombcollisions_fo_p
advance_gcinterp_b2d_vars calls include_coulombcollisions_gc_p
nu_d_fio calls cb_ei_fio
advance_fom3dc1_vars calls include_coulombcollisions_fo_p
nu_d calls cb_ei
advance_gcinterp_psiwe_vars calls include_coulombcollisions_gc_p
adv_gcinterp_psi_top calls advance_fpinterp_vars
adv_gceqn_top calls advance_fpeqn_vars
adv_gcinterp_psi2x1t_top calls advance_fpinterp_vars
adv_gcinterp_b_top calls advance_fpinterp_vars
adv_fointerp_top calls advance_fointerp_vars, advance_fp3dinterp_vars
adv_foeqn_top calls advance_fp3deqn_vars, advance_foeqn_vars
adv_gcinterp_b2d_top calls advance_fpinterp_vars
adv_fom3dc1_top calls advance_fp3dinterp_vars, advance_fom3dc1_vars
adv_gcinterp_3dbdb1_top calls advance_fpinterp_vars
adv_gcinterp_2dbdb_top calls advance_fpinterp_vars
define_collisions_time_step calls nu_s_fio, nu_s, nu_d_fio, nu_d
adv_gcinterp_psi_top_fs calls advance_fpinterp_vars
adv_gcinterp_psiwe_top calls advance_fpinterp_vars
adv_gcinterp_3dbdb_top calls advance_fpinterp_vars
main calls adv_gcinterp_psi_top, adv_gceqn_top, adv_gcinterp_psi2x1t_top, adv_gcinterp_b_top, adv_fointerp_top, adv_foeqn_top, adv_gcinterp_b2d_top, adv_fom3dc1_top, adv_gcinterp_3dbdb1_top, adv_gcinterp_2dbdb_top, define_collisions_time_step, adv_gcinterp_psi_top_fs, adv_gcinterp_psiwe_top, adv_gcinterp_3dbdb_top