#!/bin/bash

# CMake doesn't like being reconfigured completely. To avoid problems this
# will delete the CMakeCache.txt file allowing this script to start
# from a clean slate. Use the -f option on rm to silence any errors from
# rm. This makes will cause rm to ignore the error to occur if
# CMakeCache.txt doesn't exist.

BUILD_TYPE=Debug

[[ -d ./build ]] && rm -f ./build/CMakeCache.txt
[[ -d ./build ]] && rm -rf ./build/CMakeFiles

export CC=/usr/local/bin/gcc-13
export CXX=/usr/local/bin/g++-13
export FC=/usr/local/bin/gfortran-13

CMAKE_PREFIX_PATH=/usr/local/Cellar/mpich/4.1.2/lib/libmpi.dylib
#CMAKE_MPI_C_COMPILER=/usr/local/Cellar/open-mpi/4.1.5/bin/mpicc
#CMAKE_MPI_CXX_COMPILER=/usr/local/Cellar/open-mpi/4.1.5/bin/mpicxx
#CMAKE_MPI_Fortran_COMPILER=/usr/local/Cellar/open-mpi/4.1.5/bin/mpifort
CMAKE_BUILD_TYPE=$BUILD_TYPE
CMAKE_Fortran_FLAGS="\"-O3 -Wopenmp -Wallow-argument-mismatch -Walign-double\""
CMAKE_C_FLAGS="\"-O3 -Wopenmp -Walign-double\""
CMAKE_CXX_FLAGS="\"-O3 -Wopenmp -Walign-double\""
CMAKE_Fortran_FLAGS_DEBUG="\"-g -Wfpe-trap=invalid,zero,overflow -Wbacktrace\""
CMAKE_C_FLAGS_DEBUG="\"-g -W3\""
CMAKE_CXX_FLAGS_DEBUG="\"-g -W3\""
USE_PSPLINE=ON
USE_OMP=ON