fio_eval_field – KORC
fio_eval_field Interface
10 statements
Source File
interface
Called by
public function fio_eval_field(ifield, x, v, hint) bind(C, NAME='fio_eval_field')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), VALUE :: ifield
real(kind=C_DOUBLE), intent(in) :: x
real(kind=C_DOUBLE), intent(out) :: v
type(C_PTR), intent(in), VALUE :: hint
Return Value integer(kind=C_INT)
Call graph
get_m3d_c1_foelectric_fields_p calls fio_eval_field
get_m3d_c1_profile_p calls fio_eval_field
get_m3d_c1_gcelectric_fields_p calls fio_eval_field
get_m3d_c1_ion_p calls fio_eval_field
get_m3d_c1_vector_potential_p calls fio_eval_field
get_m3d_c1_fomagnetic_fields_p calls fio_eval_field
get_m3d_c1_vector_potential calls fio_eval_field
get_m3d_c1_magnetic_fields calls fio_eval_field
get_m3d_c1_electric_fields calls fio_eval_field
get_m3d_c1_gcmagnetic_fields_p calls fio_eval_field
get_m3d_c1_profile calls fio_eval_field
advance_gcinterp_m3dc1_vars calls get_m3d_c1_gcelectric_fields_p, get_m3d_c1_vector_potential_p, get_m3d_c1_gcmagnetic_fields_p, gceom1_m3dc1_p, include_coulombcollisions_gcm3dc1_p
interp_profiles calls get_m3d_c1_profile
gceom1_m3dc1_p calls get_m3d_c1_profile_p, get_m3d_c1_ion_p
interp_fields calls get_m3d_c1_vector_potential, get_m3d_c1_magnetic_fields, get_m3d_c1_electric_fields
include_coulombcollisions_gcm3dc1_p calls get_m3d_c1_profile_p, get_m3d_c1_gcelectric_fields_p, get_m3d_c1_ion_p, get_m3d_c1_vector_potential_p, get_m3d_c1_gcmagnetic_fields_p
adv_fom3dc1_top calls get_m3d_c1_foelectric_fields_p, get_m3d_c1_vector_potential_p, get_m3d_c1_fomagnetic_fields_p
fo_init calls get_m3d_c1_foelectric_fields_p, get_m3d_c1_vector_potential_p, get_m3d_c1_fomagnetic_fields_p
get_fields calls interp_fields
main calls adv_fom3dc1_top, fo_init
get_profiles calls interp_profiles
unitvectors calls get_fields
sample_hollmann_distribution_3d_psi calls get_fields
avalanche_4d calls get_profiles
mh_psi calls get_fields
get_hollmann_distribution_3d_psi calls sample_hollmann_distribution_3d_psi
get_avalanche_4d calls avalanche_4d
gyro_distribution calls unitvectors