fio_eval_field_deriv – KORC
fio_eval_field_deriv Interface
10 statements
Source File
interface
Called by
public function fio_eval_field_deriv(ifield, x, v, hint) bind(C, NAME='fio_eval_field_deriv')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), VALUE :: ifield
real(kind=C_DOUBLE), intent(in) :: x
real(kind=C_DOUBLE), intent(out) :: v
type(C_PTR), intent(in), VALUE :: hint
Return Value integer(kind=C_INT)
Call graph
get_m3d_c1_gcmagnetic_fields_p calls fio_eval_field_deriv
advance_gcinterp_m3dc1_vars calls get_m3d_c1_gcmagnetic_fields_p, include_coulombcollisions_gcm3dc1_p
include_coulombcollisions_gcm3dc1_p calls get_m3d_c1_gcmagnetic_fields_p