#!/bin/bash


__build() {


  # set default cmake build type: 'Release'
  CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"

  # list of CMake definition variables to import from existing environment
  _deflist_uptake_outset CMAKE_BUILD_TYPE

  # commit outstanding CMake def variables to the final roster
  _deflist_accrue_vars

  # convert the CMake def final roster to CMake cmdline form
  _deflist_render_cmdline

  # output the final CMake cmdline definitions
  _deflist_print_cmdline

  _debug "ci_debug __build()"

  _debug "$(pwd -P)"

  # enable xtrace
  set -x
  mkdir -p ./build && cd $_
  set +x

  _debug "$(pwd -P)"

  set -x
  cmake $CMFKIT_CMDLINE_CMAKE_DEFINITIONS .. && make
  set +x
}


__test() {

  cd ./build && make test
}

