#!/bin/bash


__import() {

  # list of CMake definition variables to import from existing environment
  _deflist_uptake_outset CMAKE_BUILD_TYPE

  # commit outstanding CMake def variables to the final roster
  _deflist_accrue_vars
}


__build() {

  # set default cmake build type: 'Release'
  CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Release}"

  # commit outstanding CMake def variables to the final roster
  _deflist_accrue_vars

  # convert the CMake def final roster to CMake cmdline form
  _deflist_render_cmdline

  # output the final CMake cmdline definitions
  _deflist_report_cmdline

  mkdir -p ./build && cd $_
  cmake $CMFKIT_CMDLINE_CMAKE_DEFINITIONS .. && make
}


__test() {

  local readonly input_file="./input_file_regtest1.korc"
  #local readonly output_file="regtest1.txt"
  local readonly output_dir="OUT_TEST"

  cd ./test/reg_tests
  mkdir -p ${output_dir}

  _debug "__test() pwd"
  pwd

  _debug "__test() find / -name xkorc"
  find / -name xkorc

  /usr/local/src/korc/build/build/bin/xkorc ${input_file} ${output_dir}/
}

