#!/bin/bash


__import() {

  # list of CMake definition variables to import from existing environment
  _deflist_uptake_outset CMAKE_BUILD_TYPE

  # commit outstanding CMake def variables to the final roster
  _deflist_accrue_vars
}


__build() {

  # set default cmake build type: 'Release'
  CMAKE_BUILD_TYPE="\"${CMAKE_BUILD_TYPE:-Release}\""

  # set compiler flag hdf5 double precision
  CMAKE_Fortran_FLAGS="\"-DHDF5_DOUBLE_PRESICION\""
  CMAKE_Fortran_FLAGS_DEBUG="\"-g -ffpe-trap=invalid,zero,overflow\""
  USE_OMP=ON
  USE_PSPLINE=ON

  # commit outstanding CMake def variables to the final roster
  _deflist_accrue_vars

  # convert the CMake def final roster to CMake cmdline form
  _deflist_render_cmdline

  # output the final CMake cmdline definitions
  _deflist_report_cmdline

  mkdir -p ./build && cd $_

  echo $CMFKIT_CMDLINE_CMAKE_DEFINITIONS

  set -x

  cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_Fortran_FLAGS="-DHDF5_DOUBLE_PRESICION -fopenmp" -DCMAKE_Fortran_FLAGS_DEBUG="-g -ffpe-trap=invalid,zero,overflow" -DUSE_OMP=ON ..

  return $?

  cmake $CMFKIT_CMDLINE_CMAKE_DEFINITIONS .. && make VERBOSE=1 \
    || return 1
}


__test() {

  local readonly input_file="../../.cmfkit/testbank/egyro/input_file_egyro.korc"
  local readonly output_dir="OUT_TEST"
  local lc

  cd ./test/reg_tests
  mkdir -p ${output_dir}

  ../../build/build/bin/xkorc ${input_file} ${output_dir}/ \
     > ${output_dir}/korc_regression_stdout.log \
     > ${output_dir}/korc_regression_stderr.log

  read lc <<< $(
    cat ${output_dir}/korc_regression_stderr.log | wc -l
  )

  [[ ${lc} -eq 0 ]] \
    || _error "regression test failure: ${input_file}" \
    || return 1
}

