---

name: agate
on:
  workflow_dispatch:

jobs:

  job_driver:
    strategy:
      matrix:

        platform:
          - macos-latest
          - ubuntu-latest
          - self-hosted

        toolchain:
          - nvhpc-openacc
          - gfortran

        mpi_impl:
          - mpich_cray
          - mpich_intel
          - openmpi
          - NoMPI

    uses: ./.github/workflows/agave.yml
    with:
      platform:   ${{ matrix.platform }}
      toolchain:  ${{ matrix.toolchain }}
      mpi_impl:   ${{ matrix.mpi_impl }}


      