---

name: agate
on:
  workflow_dispatch:

jobs:

  job_matrix:
    strategy:
      matrix:

        platform:
          - macos-latest
          - ubuntu-latest
          - self-hosted

        toolchain:
          - nvhpc-openacc
          - gfortran

        mpi:
          - mpich
          - openmpi

    uses: ./.github/workflows/agave.yml
    with:
      platform:   ${{ matrix.platform }}
      toolchain:  ${{ matrix.toolchain }}
      mpi_impl:   ${{ matrix.mpi }}


